### ISSUE TITLE
ValueError: Mismatch between the number of provided labels (376) and the number of regions in provided label image (377).

### ISSUE THREAD

**Issue by JohannesWiesner** [nilearn/nilearn#3708] opened 2023-04-19 12:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

 Linux Ubuntu 22.04

### Python version

- [ ] 3.11
- [ ] 3.10
- [X] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.0

### Expected behavior

I am using `NiftiLabelsMasker` to mask my statistical images.  I would like to use the `generate_report()` method to create an .html file. Intuitively you expect that the `labels_img` has n_regions + 1 (which correspond to a `0`) values and the `labels` argument corresponds to a list-like objects with a length of n_regions (without the 0, because it doesn't really make sense to describe the background as a region of its own). In other words: The number of regions in the image should always have one value more than the provided labels object.

### Current behavior & error messages

```bash
ValueError: Mismatch between the number of provided labels (400) and the number of regions in provided label image (401).
```

### Steps and code to reproduce bug

```python
from nilearn import datasets
from nilearn.maskers import NiftiLabelsMasker
import numpy as np
from nilearn.image import load_img

# download a single statistical image
motor_images = datasets.fetch_neurovault_motor_task()
stat_img = motor_images.images[0]

# get an atlas
atlas_data = datasets.fetch_atlas_schaefer_2018()

# get the atlas image. This has 401 values, with the 0 included
atlas_img = load_img(atlas_data['maps'])
print(len(np.unique(atlas_img.get_fdata())))

# get the atlas labels. This has only 400 values, because it doesn't make
# sense to describe a 'background region' that corresponds to the value 0.
atlas_labels = atlas_data.labels.tolist()

# set a masker
masker = NiftiLabelsMasker(labels_img=atlas_img,labels=atlas_labels)

# mask the image
masker.fit(stat_img)

# generate a report 
report = masker.generate_report()

```

You can 'solve' this by doing:

```python
atlas_labels.insert(0,'Background')
masker = NiftiLabelsMasker(labels_img=atlas_img,labels=atlas_labels)
masker.fit(stat_img)
report = masker.generate_report()
report.open_in_browser()
```

**Comment by ymzayek** [comment] 2023-04-19 17:10
Hi @JohannesWiesner, this has been reported before and is referenced in this issue: https://github.com/nilearn/nilearn/issues/3085. We will try to get a fix going. A PR is always welcome if you are up for it!

**Comment by jeromedockes** [comment] 2023-05-24 16:50
it's not entirely clear if it is better to give a name to the background and thus have 401 regions and 401 region names, or to have 401 regions and 400 region names as suggested in the issue description. but in any case the atlas fetcher and the masker should agree on this, so providing `fetch_atlas().labels` directly to `LabelsMasker` should work

**Comment by JohannesWiesner** [comment] 2023-05-30 10:08
> it's not entirely clear if it is better to give a name to the background and thus have 401 regions and 401 region names, or to have 401 regions and 400 region names as suggested in the issue description.

Hm, you're right. I guess this would be more or less a UX question then. I personally would be in favor of **not** describing a background region as a region itself, because

1.) There's already the `background_label` option in all masker classes where you can define which integer maps onto the background
2.) The majority of atlases that one would download come with some sort of `.txt`, `.csv` sidecar that maps region indices to names or even to higher-order regions and I personally have never seen the description of a background region in those files.
3.) Often you would like to continue using the sidecar for plotting purposes after masking the images. But after masking it does not make sense anymore to describe a background region because all voxels with the background label get dropped and on top one would not be interested to describe the background in the first place.

**Comment by Remi-Gau** [comment] 2023-12-23 09:56
closing this as this is a duplicate of #3085

**Closed by Remi-Gau** 2023-12-23 09:56 UTC
Labels: Bug, Atlas, Duplicate
