### ISSUE TITLE
Asymmetric colormap option for plotting.plot_stat_map

### ISSUE THREAD

**Issue by neuromichael** [nilearn/nilearn#2165] opened 2019-10-09 15:22 UTC
Hi, there. An asymmetric colormap option for plotting.plot_stat_map would be fantastic. Thank you!

**Comment by jeromedockes** [comment] 2019-10-09 15:37
I am not sure this will be added, to avoid misleading plots where e.g.
positive values are plotted in red with the "cold_hot" cmap.
but in the meanwhile you can use `plot_img`, which is more flexible than
`plot_stat_map`

**Comment by GaelVaroquaux** [comment] 2019-10-09 15:47
> Hi, there. An asymmetric colormap option for plotting.plot_stat_map would be fantastic.

Does the 'symmetric_cbar' solve the issue?

If so, we need to document it better. Do you have a suggestion on how to
improve.

If not, can you tell us more.

**Comment by NicolasGensollen** [comment] 2021-01-13 11:16
Hi @neuromichael 
As has been said above, you can set `symmetric_cbar` to `False` to display an asymmetric colorbar, but there is no user-friendly way to use asymmetric colormaps by design:

https://github.com/nilearn/nilearn/blob/bb3cd501add9f29e108d5fa4c21a2412579545bb/nilearn/plotting/img_plotting.py#L1119-L1123

I don't believe this feature will be implemented as pointed out above. Unless you feel this should stay open, I will close this issue in a few weeks.

**Comment by bthirion** [comment] 2021-01-13 14:10
Closing, as `plot_img` does the trick.

**Closed by bthirion** 2021-01-13 14:10 UTC
Labels: stalled
