### ISSUE TITLE
Online reference seems broken

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#779] opened 2015-09-10 06:17 UTC
It seems to me that in the reference page,  many functions are missing

**Comment by dohmatob** [comment] 2015-09-10 06:35
For example which one ? (So one can check the generated doc pages on circle ci)

**Comment by GaelVaroquaux** [comment] 2015-09-10 08:07
On page:
http://nilearn.github.io/modules/reference.html

decoding, decomposition, image, plotting, input_data, amongst other have
no function listed at all.

**Comment by dohmatob** [comment] 2015-09-10 11:43
OK, thanks.

On Thu, Sep 10, 2015 at 10:07 AM, Gael Varoquaux <notifications@github.com>
wrote:

> On page:
> http://nilearn.github.io/modules/reference.html
>
> decoding, decomposition, image, plotting, input_data, amongst other have
> no function listed at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/779#issuecomment-139160562>.
>



-- 
DED

**Comment by dohmatob** [comment] 2015-09-10 13:52
Ok, a fix should amount to added **Functions** subsections in `doc/modules/reference.rst` under the appropriate topics. This can be semi-automated by simply scraping all modules for "public" `def`s (i.e with the function name not beginning with underscore `_`), and then grabbing the function name. The so-created list of function names would then be inserted in the aforementioned .rst file. I can roll a PR.

**Comment by GaelVaroquaux** [comment] 2015-09-10 13:57
> Ok, a fix should amount to added Functions subsections in doc/modules/
> reference.rst under the appropriate topics.

I wonder if there is not another people: a quick glance at this file
shows that at least some of the functions seem to be there.

**Comment by dohmatob** [comment] 2015-09-10 14:26
Ya indeed. also note that the github.io refs are missing some stuff already
present in the dev.

On Thu, Sep 10, 2015 at 3:57 PM, Gael Varoquaux <notifications@github.com>
wrote:

> > Ok, a fix should amount to added Functions subsections in doc/modules/
> > reference.rst under the appropriate topics.
>
> I wonder if there is not another people: a quick glance at this file
> shows that at least some of the functions seem to be there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/779#issuecomment-139242132>.
>



-- 
DED

**Comment by dohmatob** [comment] 2015-09-10 14:26
OK, this can probably be done by somebody else. I've just created an initial list of function names to be included in .rst (see previous msg) to help.

Plugin #0: decoding
tvl1_solver
spectral_norm_squared
search_light
mfista
search_light
Plugin #1: decomposition
session_pca
Plugin #2: image
to_matrix_vector
from_matrix_vector
coord_transform
get_bounds
get_mask_bounds
resample_img
reorder_img
high_variance_confounds
smooth_img
crop_img
mean_img
swap_img_hemispheres
index_img
iter_img
new_img_like
Plugin #3: plotting
alpha_cmap
dim_cmap
replace_inside
plot_brain_schematics
find_xyz_cut_coords
find_cut_slices
get_create_display_fun
get_slicer
get_projector
check_threshold
add_brain_schematics
show
plot_img
plot_anat
plot_epi
plot_roi
plot_prob_atlas
plot_stat_map
plot_glass_brain
plot_connectome
Plugin #4: input_data
filter_and_extract
check_embedded_nifti_masker
filter_and_mask

**Generated with**: `index=0; for plugin in decoding decomposition image plotting input_data; do echo "Plugin #${index}: ${plugin}"; egrep --color "^def " -R nilearn/${plugin} | egrep -v "test" | egrep -v "def _" | egrep -v "master" | cut -d":" -f2 | cut -d" " -f2 | cut -d"(" -f1; index=$((index + 1)); done > missing_func_refs.txt`

**Comment by lesteve** [comment] 2015-09-22 09:35
This is a duplicate of #712. Closing.

**Closed by lesteve** 2015-09-22 09:35 UTC
