### ISSUE TITLE
make docs requires a big download

### ISSUE THREAD

**Issue by chrisfilo** [nilearn/nilearn#669] opened 2015-07-14 17:33 UTC
filo at MathBook Pro in /nilearn/doc on plot-glass-brain-negative-values [!]
	$ make
	sphinx-build -D plot_gallery=False -b html -d _build/doctrees   . _build/html
	Running Sphinx v1.3.1
	WARNING: invalid number u'False' for config value 'plot_gallery', ignoring
	loading translations [en]... done
	loading pickled environment... not yet created
	plotting plot_nifti_simple.py
	Downloading data from http://www.nitrc.org/frs/download.php/1071/NYU_TRT_session1a.tar.gz

**Comment by AlexandreAbraham** [comment] 2015-07-15 10:26
There seems to be a problem with your sphinx-gallery: it does not recognize the option `plot_gallery=False` properly and so it tries to build the examples, which require data.

Can you update your sphinx-gallery and tell us if the problem still holds?

**Comment by GaelVaroquaux** [comment] 2015-07-15 10:27
Chris and I were not able to reproduce, including on his laptop.

**Comment by AlexandreAbraham** [comment] 2015-07-15 11:05
Should we close it, then?

**Comment by GaelVaroquaux** [comment] 2015-07-15 11:06
> Should we close it, then?

Chris?

**Comment by GaelVaroquaux** [comment] 2015-07-16 08:02
Closing

**Closed by GaelVaroquaux** 2015-07-16 08:02 UTC
