### ISSUE TITLE
Resampling of mask_img does not remove background noise.

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1171] opened 2016-07-07 12:42 UTC
I am trying to do use `NiftiMasker` to get the signals within a region given by a binary mask. It works when I manually resample the mask to the shape and affine of my functional image, but when using the masker reasmpling I am getting an error. May be I am doing something wrong with the `NiftiMasker` ?

``` Python
import nibabel
from nilearn import datasets, masking, input_data
icbm152 = datasets.fetch_icbm152_2009()
wm_filename = icbm152.wm
wm_mask_img = masking.compute_epi_mask(wm_filename, upper_cutoff=1.)
adhd = datasets.fetch_adhd(n_subjects=1)
func_img = nibabel.load(adhd.func[0])
target_shape, target_affine = func_img.get_data().shape[:-1], func_img.get_affine()
wm_masker = input_data.NiftiMasker(mask_img=wm_mask_img,
                                   target_shape=target_shape,
                                   target_affine=target_affine)
wm_signals = wm_masker.fit_transform(adhd.func[0])
```

throughs the following error

> ValueError: Given mask is not made of 2 values: [ -7.44326475e-15  -7.13535134e-15  -6.32653652e-15 ...,   6.93715918e-15
>    7.04167627e-15   1.00000000e+00]. Cannot interpret as true or false

**Comment by AlexandreAbraham** [comment] 2016-07-19 13:05
What happens if that nilearn resamples the mask and, when trying to load it, is bothered by the numerical noise in the background. We should have a special function to resample a mask (ie binarize the values after resampling).

**Comment by NicolasGensollen** [comment] 2020-12-21 15:11
I can't reproduce the error with the provided code. Should we close this?

Here is the updated version to get rid of the deprecation warnings:

```python
import nibabel
from nilearn import datasets, masking, input_data
from nilearn.image import get_data

icbm152 = datasets.fetch_icbm152_2009()
wm_filename = icbm152.wm
wm_mask_img = masking.compute_epi_mask(wm_filename, upper_cutoff=1.)
adhd = datasets.fetch_adhd(n_subjects=1)
func_img = nibabel.load(adhd.func[0])
target_shape, target_affine = get_data(func_img).shape[:-1], func_img.affine
wm_masker = input_data.NiftiMasker(mask_img=wm_mask_img,
                                   target_shape=target_shape,
                                   target_affine=target_affine)
wm_signals = wm_masker.fit_transform(adhd.func[0])
```

**Comment by jeromedockes** [comment] 2020-12-21 16:10
can't reproduce either. I think we can close it

**Closed** 2020-12-21 16:40 UTC
Labels: Bug, Important
