### ISSUE TITLE
Urgent: Memory error when scaling NiftiSpheresMasker to run on multiple datasets in parallel.

### ISSUE THREAD

**Issue by dPys** [nilearn/nilearn#1663] opened 2018-06-27 03:45 UTC
Occurs with and without the use of joblib, and regardless of whether 4d nifiti input is compressed/uncompressed. Thoughts?
```
 File "/opt/conda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.6/site-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 17, in extract_ts_coords
  File "/opt/conda/lib/python3.6/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 275, in fit_transform
    return self.fit().transform(imgs, confounds=confounds)
  File "/opt/conda/lib/python3.6/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/opt/conda/lib/python3.6/site-packages/nilearn/input_data/nifti_spheres_masker.py", line 321, in transform_single_imgs
    verbose=self.verbose)
  File "/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py", line 283, in __call__
    return self.func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/nilearn/input_data/base_masker.py", line 66, in filter_and_extract
    imgs = _utils.check_niimg(imgs, atleast_4d=True, ensure_ndim=4)
  File "/opt/conda/lib/python3.6/site-packages/nilearn/_utils/niimg_conversions.py", line 271, in check_niimg
    niimg = load_niimg(niimg, dtype=dtype)
  File "/opt/conda/lib/python3.6/site-packages/nilearn/_utils/niimg.py", line 116, in load_niimg
    dtype = _get_target_dtype(niimg.get_data().dtype, dtype)
  File "/opt/conda/lib/python3.6/site-packages/nibabel/dataobj_images.py", line 202, in get_data
    data = np.asanyarray(self._dataobj)
  File "/opt/conda/lib/python3.6/site-packages/numpy/core/numeric.py", line 544, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/opt/conda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 293, in __array__
    raw_data = self.get_unscaled()
  File "/opt/conda/lib/python3.6/site-packages/nibabel/arrayproxy.py", line 288, in get_unscaled
    mmap=self._mmap)
  File "/opt/conda/lib/python3.6/site-packages/nibabel/volumeutils.py", line 523, in array_from_file
    data_bytes = bytearray(n_bytes)
MemoryError
```

**Comment by GaelVaroquaux** [comment] 2018-06-27 05:33
> Occurs with and without the use of joblib. Thoughts?

You don't have enough memory to open multiple of these files.

**Comment by AlexandreAbraham** [comment] 2018-06-27 06:39
Hello Derek,
As Gael said, it is probably linked to memory consumption. Can you give us a glimpse of your data size ? How many files and how many spheres you are extracting?
Thanks!

**Comment by dPys** [comment] 2018-06-27 13:41
Thanks much @GaelVaroquaux and @AlexandreAbraham for the quick reply! 

This occurs when I load the same 4D nifti (2.27 gb) many times simultaneously. 5 atlases (k=50, 100, 150, 200, and 250 nodes) x 5 node sizes (2,3,4,5,6) = 25 different NiftiSpheresMasker operations in parallel, to be exact. Each of these threads is contained within a nipype function Node. I've tried restricting the function Node to 2 threads and up to 20 gb of memory, but this has little or no impact. On the one hand, I'm applying multiple independent operations to the same large data object simultaneously, but the issue persists even if I stagger the function calls with random interval sleep commands, so I'm skeptical that this totally explains what's happening...

**Comment by dPys** [comment] 2018-06-27 13:50
FYI: This is a continuation of this issue (I want to make sure both the Nilearn + Nipype sides of this get covered): 
[](https://github.com/nipy/nipype/issues/2622)

**Comment by GaelVaroquaux** [comment] 2018-06-27 13:57
> so I'm skeptical that this totally explains what's happening...

It's a MemoryError. You don't have enough memory. The multiple layers of
code are probably not very memory efficient. But at the end of the day,
the problem is that the computer runs out of memory.

**Comment by dPys** [comment] 2018-06-27 15:07
Yep. It's confusing though, because every other function across all other layers of code scales perfectly fine. Why not _this_ function in particular?

**Comment by KamalakerDadi** [comment] 2018-06-27 19:16
Small suggestion: I think in your case, I would try to reduce the layers to simple. That is atlas by atlas and node by node. Since you are trying this on single subject it shouldn't take too long. AFAIK.

This could also helps in diagnose the problem.

>As an aside, how do NiftiSpheresMasker's memory requirements scale based on number of nodes?

I haven't tried many nodes but only 5. I tried this on ABIDE data which is large and have not seen any issues.

**Comment by dPys** [comment] 2018-06-27 21:44
Thanks for the suggestion @KamalakerDadi 
I think you're on the right track. Will try a few more things and report back!

**Comment by GaelVaroquaux** [comment] 2018-07-02 12:06
Closing this issue as it is not a nilearn one.

**Closed by GaelVaroquaux** 2018-07-02 12:06 UTC

**Comment by dPys** [comment] 2018-07-03 02:05
Thank you @GaelVaroquaux . By the way-- you were very right. When it came down to it, just a memory error. 🙏
