### ISSUE TITLE
Greyscale colorbar with plot_prob_atlas

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1110] opened 2016-06-07 15:26 UTC
See #1026

**Comment by NicolasGensollen** [comment] 2021-01-04 13:16
I looked at #1026 and it looks like this issue is related to a problem you were having @bthirion with a colorbar in grayscale which couldn't be reproduced at the time. 
Since this was with Python 2.7 and old versions of dependencies that we don't support anymore, it will be hard to dig into this. I was wondering whether you still have this issue or if we could close this.

**Comment by bthirion** [comment] 2021-01-04 20:42
Looks like time has solved the issue ! Closing, thx.

**Closed by bthirion** 2021-01-04 20:42 UTC

**Comment by bthirion** [comment] 2021-01-07 10:00
Closing for now.
