### ISSUE TITLE
Unzipping tar.gz file is failing in nilearn.dataset.utils._uncompress_file

### ISSUE THREAD

**Issue by swaythe** [nilearn/nilearn#2569] opened 2020-09-23 09:42 UTC
Hi all,

I'm trying to run a pypreprocess example that downloads and processes a tar.gz file from FSL. The download happens fine but the script fails during the extraction process with an error saying the file is not a gzipped file. When I tried to debug it looks like the script fails in nilearn.dataset.utils._uncompress_file, in the part before the supposed handling of tar.gz files. The file itself is fine, I can uncompress it on my own, and run the pypreprocess example script with a pre-downloaded and uncompressed file. Could someone please take a look?

Thanks!

Here's the error traceback:

Error uncompressing file: Not a gzipped file (b'fe')
Archive corrupted, trying to download it again.
Downloading data from http://fsl.fmrib.ox.ac.uk/fsldownloads/oldversions/fsl-4.1.0-feeds.tar.gz ...
Downloaded 278290310 of 277930287 bytes (100.1%,   -0.0s remaining) ...done. (38 seconds, 0 min)
Error uncompressing file: Not a gzipped file (b'fe')
Extracting data from /home/sshankar/nilearn_data/fsl_feeds/fsl-4.1.0-feeds.tar.gz...Traceback (most recent call last):
  File "/home/sshankar/pypreprocess/build/py3k/pypreprocess/datasets.py", line 178, in fetch_fsl_feeds
    _uncompress_file(archive_path)
  File "/home/sshankar/nilearn/nilearn/datasets/utils.py", line 357, in _uncompress_file
    shutil.copyfileobj(gz, out, 8192)
  File "/usr/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'fe')

**Comment by jeromedockes** [comment] 2020-09-23 10:15
Hello, can you share the script (or a stripped-down version to reproduce
the error)?
are you using a nilearn fetcher or one of the dataset utilities directly?

thanks

**Comment by swaythe** [comment] 2020-09-23 10:49
Here's the relevant part:

-------------------------------
try:
    from nilearn.datasets.utils import (_fetch_file, _fetch_files,
                                        _uncompress_file, _get_dataset_dir)
except ImportError:
    # old version, or change not yet in release
    from nilearn.datasets import (_fetch_file, _fetch_files,
                                  _uncompress_file, _get_dataset_dir)

data_dir = _get_dataset_dir(data_name, data_dir=data_dir,
                                verbose=verbose)

def _glob_fsl_feeds_data(subject_dir):
        """glob data from subject_dir.

        """

    # download the data
    print("Data absent, downloading...")
    url = ("http://fsl.fmrib.ox.ac.uk/fsldownloads/oldversions/"
           "fsl-4.1.0-feeds.tar.gz")
    archive_path = os.path.join(data_dir, os.path.basename(url))
    for i in range(2):
        _fetch_file(url, data_dir)
        try:
            _uncompress_file(archive_path)
            break
        except:
            if i == 0:
                print("Archive corrupted, trying to download it again.")
                os.remove(archive_path)
            else:
                raise IOError("Unable to download archive from %s" % url)
    return _glob_fsl_feeds_data(data_dir)

---------------------------------

Thanks.

**Comment by jeromedockes** [comment] 2020-09-23 11:32
That's because requests uncompresses the gzipped data on the fly and
_uncompress relies on the file name
use:

```
_fetch_files(
    data_dir, [("feeds", url, {"uncompress": True, "move": "fsl.tar"})]
)
```

note, all of these start with an underscore: they are private
functions -- there is in theory no support for using them directly and
they can change without notice. Are you preparing a new fetcher for
nilearn or for a separate project?

**Comment by jeromedockes** [comment] 2020-09-23 11:52
Note that the problem is a mistake from the server from which you download the
data: it advertises the 'Content-Encoding' as 'gzip' and the 'Content-Type' as
'application/x-gzip', which means that decompressing the response with gzip
should yield a gzip file. the actual content encoding used by the server is
'identity'

(see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding)

**Comment by swaythe** [comment] 2020-09-23 12:14
Thanks for that! The script I was running has long been a part of pypreprocess and was working fine a couple of weeks ago but failed yesterday. I think I updated nilearn in the between the time the script worked and stopped working, so wondered if something had changed with how nilearn uncompresses.

I'll use _fetch_files and see how it goes.

**Comment by jeromedockes** [comment] 2020-09-23 12:38
> Thanks for that! The script I was running has long been a part of pypreprocess and was working fine a couple of weeks ago but failed yesterday. I think I updated nilearn in the between the time the script worked and stopped working, so wondered if something had changed with how nilearn uncompresses.
>
I guess you are using the source from the repo, not the latest release?
In that case something has changed in how files are downloaded, not how
they are uncompressed. the library that we now use to download the file
reads the content-encoding header and decodes the data, but in this case
this header is incorrect.

**Comment by swaythe** [comment] 2020-09-23 13:58
> Thanks for that! The script I was running has long been a part of pypreprocess and was working fine a couple of weeks ago but failed yesterday. I think I updated nilearn in the between the time the script worked and stopped working, so wondered if something had changed with how nilearn uncompresses.
> I guess you are using the source from the repo, not the latest release? In that case something has changed in how files are downloaded, not how they are uncompressed. the library that we now use to download the file reads the content-encoding header and decodes the data, but in this case this header is incorrect.
Yes, I was using the source and not the latest release. Thanks for the looking into this and for the explanation!

**Comment by jeromedockes** [comment] 2020-09-23 14:09
> Yes, I was using the source and not the latest release. Thanks for the looking into this and for the explanation!

No problem! I guess we can close this issue?

**Closed** 2020-09-23 14:10 UTC
