### ISSUE TITLE
Deprecated function used in plotting ? 

### ISSUE THREAD

**Issue by chrisfoulon** [nilearn/nilearn#1381] opened 2017-02-15 12:17 UTC
Hi nilearn team, thanks for you great work !

I just started to learn to use your functions and I tried to use you plotting function and got the following error : 
<nilearn.plotting.displays.OrthoSlicer at 0x7f22cbd27e80>
/usr/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

So as you can see I have python 3.6 and matplotlib seems to be upgraded to the latest version. 

Did I make a mistake ? 

Thank you in advance ! 

Chris Foulon.

**Comment by GaelVaroquaux** [comment] 2017-02-15 12:19
> So as you can see I have python 3.6 and matplotlib seems to be upgraded to the latest version.

Do you have the development version of nilearn?

If so and that's still the case, do you want to submit a pull request
that checks for the version of MPL and uses different options depending
on the version? That would be super useful?

Thanks!

**Comment by chrisfoulon** [comment] 2017-02-15 14:05
I just installed nilearn with pip so I didn't check the code yet, I don't know if I am able to modify the function :).

**Comment by GaelVaroquaux** [comment] 2017-03-03 18:51
Closing as duplicate of #1394 (which is currently being addressed)

**Closed by GaelVaroquaux** 2017-03-03 18:51 UTC
