### ISSUE TITLE
Include Haxby hyper alignment data

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#147] opened 2013-12-10 01:46 UTC
http://data.pymvpa.org/datasets/hyperalignment_tutorial_data/

This is HDF5, so we need to do what we already did for the Kamitani dataset: reconvert it to nifti, and host it on our nilearn data repo.

Tasklist:
- [ ] Understand the data
- [ ] Turn it into nifti
- [ ] Write an example

**Comment by bcipolli** [comment] 2015-02-22 00:19
I am in need of a preprocessed functional dataset; I didn't see one in `nilearn.datasets`, so I have been taking a look at this today.

I was able to download the data, install pymvpa (non-trivail!), and load up the data.

Turns out that the HDF5 data serialized the header with an old version of `nibabel` that is incompatible with 2.0.0.  I am currently stuck here.  https://github.com/nipy/nibabel/issues/144

Any comments / concerns / duplicate efforts, please let me know!  Otherwise, I'll follow up as things go...

**Comment by bcipolli** [comment] 2015-02-22 05:18
Pretty close to having this done; something is weird about the conversion to Nifti that I need to fix.  But the basic instructions and code is all there.  Feel free to play:
https://github.com/bcipolli/nilearn/tree/haxby_etal_2011

**Comment by bcipolli** [comment] 2015-02-22 05:48
Example can be derived from: http://www.pymvpa.org/examples/hyperalignment.html

**Comment by GaelVaroquaux** [comment] 2015-02-23 06:59
No specific advice, I haven't tried doing this. However, just to let you know, if you succeed in loading these as nifti, save therm as .nii.gz and we will upload them on our nilearn site. That way other people can load them. 

Thanks heaps

Gaël

PS :  what kind of pre processed days do you need? Maybe we can help.

**Comment by bcipolli** [comment] 2015-05-05 21:15
Just a note: looks like the PyMVPA folks recoded this, so the conversion to .nii should be relatively easy now:
https://github.com/PyMVPA/PyMVPA/issues/278#issuecomment-99069421

**Comment by AlexandreAbraham** [comment] 2015-06-01 15:31
_Relatively_ is the word here. I took a quick look at the file and the format is not clear at all to me.

**Comment by bcipolli** [comment] 2015-07-13 15:09
Hi all, is anybody on the nilearn side planning to work on this? I may be able to take a look soon as well.

**Comment by AlexandreAbraham** [comment] 2015-07-13 15:15
Not for the moment given that it is not trivial ;). But you definitely have the knowledge to handle this. Do you want me to make it official by assigning it to you?

**Comment by bcipolli** [comment] 2015-07-13 15:25
I'm not sure that I have the knowledge to handle this, but I do have the will to figure it out :) Please assign to me, and I will try to work it out.

**Comment by AlexandreAbraham** [comment] 2015-07-13 15:42
> I'm not sure that I have the knowledge to handle this

Do not hesitate to report problems so that we can try to sort them out together! I sent you an invitation to join the nilearn team. Please accept it so that I can assign this issue to you ;).

**Comment by bcipolli** [comment] 2015-07-13 15:44
Done!

**Comment by AlexandreAbraham** [comment] 2015-07-13 15:45
Misclicked ;).

When do you plan to work on that? I think you may be aware that we are doing a nilearn sprint this week so, if you need support, our time is 100% dedicated to nilearn.

**Comment by bcipolli** [comment] 2015-07-13 15:49
I hope to take a look tonight or tomorrow. I've got `pymvpa` installed, the file downloaded and loaded... just need to figure out the different data there, then export to `.nii` (easy) and hopefully extract an example from the `pymvpa` tutorial.

**Comment by AlexandreAbraham** [comment] 2015-07-13 16:22
Sounds like bullet points. I added them into the first post ;).

Once you've made a script to convert the data to nifti, please keep it: we'll ship it with the transformed data.

**Comment by bcipolli** [comment] 2015-07-15 16:35
Here's where I am so far:
* downloaded data
* installed PyMVPA
* Understood data structures ~65%
* Got basic script for saving `Nifti1Image`s and stimuli.

Problems:
* Was able to use affine info, but not header info (it's a dict, can't figure out how to convert back to `Nifti1Header`)

Unfortunately, something seems slightly off. The docs said the data are in MNI152 space, so I don't think it's that. Any suggestions on where to go next would be appreciated!

![image](https://cloud.githubusercontent.com/assets/4072455/8703898/8f1aec1a-2ad4-11e5-8da3-b55d3418f534.png)

```python
            # raw_files[0] is a local path to the download of 
            # 'http://data.pymvpa.org/datasets/hyperalignment_tutorial_data/hyperalignment_tutorial_data_2.4.hdf5.gz'
            ds_all = h5load(raw_files[0])
            for si, func_filename in enumerate(processed_files[:-1]):
                if not os.path.exists(os.path.dirname(func_filename)):
                    os.makedirs(os.path.dirname(func_filename))

                # Construct and save the image
                func_data = np.transpose(ds_all[si].O, [1, 2, 3, 0])
                func_affine = ds_all[si].a['imgaffine'].value
                func_hdr = ds_all[si].a['imghdr'].value
                img = nib.Nifti1Image(func_data, affine=func_affine)#, header=func_hdr)
                nib.save(img, func_filename)

            # Construct and save the stimuli
            value_arr = np.asarray([ds_all[0].T, ds_all[0].sa['chunks']])
            csv_cols = np.vstack([['stim', 'chunk'], value_arr.T])
            np.savetxt(processed_files[-1], csv_cols, delimiter=',', fmt='%s')
```

**Comment by bcipolli** [comment] 2015-07-15 16:37
script for plotting is:
```python
import matplotlib.pyplot as plt
import nibabel as nib
from nilearn.plotting import plot_stat_map
from nilearn.image import index_img
from nilearn.datasets import fetch_haxby_hyperalign

dset = fetch_haxby_hyperalign(n_subjects=1)  # 
func_img = nib.load(dset['func'][0])
plot_stat_map(index_img(func_img, 0))
plt.show()
```

**Comment by AlexandreAbraham** [comment] 2015-07-17 09:11
Could you provide a working script? I can't reproduce your figures :-/

**Comment by bcipolli** [comment] 2015-07-17 14:33
@AlexandreAbraham Added the missing parts just now. if you replace the path to the file, should work now.

Let me know if you have a problem with the `pymvpa` import...

**Comment by thomasbazeille** [comment] 2020-04-28 07:08
Hi every one, as this seem to have been stalled for a while and the current policy is to add new datasets only with a big momentum, I guess this can be closed ?

**Closed** 2020-04-28 07:09 UTC
Labels: Datasets, Enhancement
