### ISSUE TITLE
Variable names and type rendering inconsistencies in generated documentation

### ISSUE THREAD

**Issue by jhlegarreta** [nilearn/nilearn#2328] opened 2020-03-08 13:25 UTC
The official Nilearn API/reference documentation at
http://nilearn.github.io/modules/reference.html

seems not to follow a consistent pattern:

- In some cases, some files suffer from a glitch that prevents the variable names and their types being rendered with a blank space and/or a colon in between that would greatly improve the readability, e.g. http://nilearn.github.io/modules/generated/nilearn.plotting.plot_anat.html#nilearn.plotting.plot_anat
- In other cases, such a separation between the variable names and their types exist, but they are both rendered in bold, e.g.
http://nilearn.github.io/modules/generated/nilearn.image.get_data.html#nilearn.image.get_data
- In other cases, both variants are present:
http://nilearn.github.io/modules/generated/nilearn.image.clean_img.html#nilearn.image.clean_img

Similar formatting issues seem to be present for the return data docstrings, e.g.
http://nilearn.github.io/modules/generated/nilearn.image.math_img.html#nilearn.image.math_img

Making the rendering of the docstrings consistent across the toolkit would improve the readability of the documentation.

**Comment by bthirion** [comment] 2020-03-09 20:28
Thx for the comments. Do you want to open a PR ?

**Comment by GaelVaroquaux** [comment] 2020-03-09 21:06
It's related to inconsistent space vs no space in front of the colon
(":") in the docstrings:
https://github.com/nilearn/nilearn/blob/master/nilearn/image/image.py#L924

Proper rendering calls for no space.

A PR to fix this would be great!

**Comment by jhlegarreta** [comment] 2020-03-10 09:36
Thanks both for having paid attention to this.

I would be willing to propose a PR. Yet, the behavior does not seem to be consistent. NumPy's docstrings do introduce a whitespace around the colon, so I am not sure exact reason. May be the extension used to render the documentation? Also, for the method pointed, the boldface is not applied to the return value docstring. And finally, I'd dare to say that having the types in italics would help towards a more readable documentation, as in NumPy's documentation.

Thus, I am wondering whether I am missing something else to fully understand the behavior of the documentation rendering in Nilearn.

**Comment by GaelVaroquaux** [comment] 2020-05-20 09:38
Link to the numpy doc standard: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html

**Comment by ZviBaratz** [comment] 2020-05-20 11:10
According to NumPy's docstring standard spaces are required, however they are not rendered properly. Should we stick to what renders well or fix what's causing the rendering issue?

**Comment by bthirion** [comment] 2020-05-20 12:04
@GaelVaroquaux does this result from a sphinx bug ?

**Comment by GaelVaroquaux** [comment] 2020-05-20 12:18
Actually, the above link is the napoleon interpretation of the standard, and we, in nilearn, are using the numpydoc's interpretation:
https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by ZviBaratz** [comment] 2020-05-20 12:53
I made a PR with fixes to the `image.py` module, if the changes are acceptable I will try to do the same in as many modules as I can in the next couple of days. If I see I won't be able to go over all of them, I'll just fix the spacing inconsistencies without really going over the docstrings themselves so that at least this issue is resolved.

**Comment by jhlegarreta** [comment] 2020-05-20 13:52
Thanks for trying to cast some light on this ! I apologize for not having made progress on this, but since the behavior was not consistent, I did not investigate further.

> According to NumPy's docstring standard spaces are required, however they are not rendered properly. Should we stick to what renders well or fix what's causing the rendering issue?

> @GaelVaroquaux does this result from a sphinx bug ?

I'd say that if this is an issue on the Sphinx side, we may want to open an issue in their GitHub. I can do that/ask. Let me know if this is likely to be the cause. I'd like to think that whether a whitespace exists or not, the colon should be enough/the key to apply the proper style.

Otherwise, docstrings in `NumPy` are rendered with the appropriate style and they advocate for having whitespaces.

@ZviBaratz I have visited PR #2450. The [image:clean_img:sessions](https://github.com/nilearn/nilearn/blob/master/nilearn/image/image.py#L927) parameter did contain the whitespaces, but is not being rendered correctly and the style is not being applied, and hence it was not clear to me where the error stemmed from.

Maybe all of this has to do with the style sheet that you are changing in your PR #2450?

**Comment by ZviBaratz** [comment] 2020-05-20 14:31
@GaelVaroquaux actually proposed we simply add a custom CSS rule to add a margin, which seems to have a good-looking result, so the issue is technically resolved. Once the spaces are fixed everything should render smoothly.

**Comment by jhlegarreta** [comment] 2020-05-20 14:40
> @GaelVaroquaux actually proposed we simply add a custom CSS rule to add a margin, which seems to have a good-looking result, so the issue is technically resolved. Once the spaces are fixed everything should render smoothly.

OK. Do the CI builds build the documentation to see the how they look like after a PR that affects the documentation?

**Comment by bthirion** [comment] 2020-05-20 14:54
circleci does. If it's not broken...

**Comment by thomasbazeille** [comment] 2020-05-20 14:59
> OK. Do the CI builds build the documentation to see the how they look like after a PR that affects the documentation?

You'll be able to see it under the CircleCI "push" category of checks for the PR when it's done, then when you go to this page in the "Artifacts" section.

**Comment by jhlegarreta** [comment] 2020-05-20 15:08
> circleci does. If it's not broken...

> You'll be able to see it under the CircleCI "push" category of checks for the PR when it's done, then when you go to this page in the "Artifacts" section.

👍 Thanks. Will have a look when the build finishes.

**Comment by jhlegarreta** [comment] 2020-05-22 20:38
Looks like the build that should have generated the artifact unfortunately failed :worried:, so I guess I have no way to check this.

I ignore if the latest doc is pushed regularly/nightly to the website. If it gets pushed, I am not sure the PR has been successful in addressing the issue (e.g. having a look at [image:clean_img:sessions](https://github.com/nilearn/nilearn/blob/master/nilearn/image/image.py#L927)), but if you have been able to check it otherwise, please update the issue, and close if necessary.

Otherwise, let me know how I can help.

**Comment by bthirion** [comment] 2020-05-23 07:37
IIUC, this is superseded by #2478 (but the build  has also failed).

**Comment by jhlegarreta** [comment] 2020-05-23 15:57
@bthirion thanks for the note !

@GaelVaroquaux thanks for proposing the fix ! If it is believed to be working, you may be willing to get this issue closed automatically when the PR gets merged by adding the appropriate message to the PR.

**Comment by tsalo** [comment] 2020-06-30 21:05
I noticed that #2478 was merged, but it pivoted away from using napoleon and some of the variable/type rendering issues still seem to be around. I’d be happy to take a crack at fixing the issue, whether by reformatting all of the docstrings or switching to napoleon. 

I tested out napoleon with nilearn locally and the results looked pretty good (the variable/type spacing issue seems to be fixed), but I don’t want to open a PR with the changes if it’s not something the devs want done. I also only ran with `noplot`, so if there is a problem specifically with the examples I may not have seen it.

**Comment by bthirion** [comment] 2020-06-30 21:30
@GaelVaroquaux at some point you gave up with Napoleon: what is your opinion ?

**Comment by thomasbazeille** [comment] 2020-09-16 10:42
@GaelVaroquaux can you answer last two comments ? Should this issue remain open ?

**Comment by bthirion** [comment] 2021-04-19 16:27
Stalled, closing.

**Closed by bthirion** 2021-04-19 16:27 UTC
Labels: Documentation, Good first issue, code quality

**Comment by jhlegarreta** [comment] 2021-04-25 15:31
@bthirion @GaelVaroquaux @tsalo @jeromedockes @NicolasGensollen thanks for persevering and for having finally addressed these across several PRs. I had a look at the files I linked at the beginning of this issue, and all docstrings look good now. Great work :100:.

**Comment by bthirion** [comment] 2021-04-25 17:03
Thx for checking !
