### ISSUE TITLE
fit_transform() methd show resampling.BoundingBoxError

### ISSUE THREAD

**Issue by poppintiger** [nilearn/nilearn#1870] opened 2018-11-26 08:47 UTC
I was trying to convert a fmri rest data(4D) to a roi time series format:

` dataset = image.load_img(fmir_path);
  compcor = high_variance_confounds(dataset, n_confounds=5);
  time_series = masker.fit_transform(dataset, confounds=compcor)`

But, when I run above code, it showed following error：
**nilearn.image.resampling.BoundingBoxError: The field of view given by the target affine does not contain any of the data**

So I want to know what might be cause of the error?  Is that my data not in the MNI space? or something else?

**Comment by poppintiger** [comment] 2018-11-26 08:53
**This is the whole error track：**
`---> 45 time_series = masker.fit_transform(dataset, confounds=compcor)
     46 print(np.shape(time_series))
     47 print((time_series))

~\Anaconda3\envs\tensorflow\lib\site-packages\nilearn\input_data\nifti_labels_masker.py in fit_transform(self, imgs, confounds)
    189         """ Prepare and perform signal extraction from regions.
    190         """
--> 191         return self.fit().transform(imgs, confounds=confounds)
    192 
    193     def _check_fitted(self):

~\Anaconda3\envs\tensorflow\lib\site-packages\nilearn\input_data\base_masker.py in transform(self, imgs, confounds)
    174         self._check_fitted()
    175 
--> 176         return self.transform_single_imgs(imgs, confounds)
    177 
    178     def fit_transform(self, X, y=None, confounds=None, **fit_params):

~\Anaconda3\envs\tensorflow\lib\site-packages\nilearn\input_data\nifti_labels_masker.py in transform_single_imgs(self, imgs, confounds)
    232                         self.labels_img_, interpolation="nearest",
    233                         target_shape=imgs_.shape[:3],
--> 234                         target_affine=imgs_.affine)
    235 
    236         target_shape = None

~\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\externals\joblib\memory.py in __call__(self, *args, **kwargs)
    360 
    361     def __call__(self, *args, **kwargs):
--> 362         return self.func(*args, **kwargs)
    363 
    364     def call_and_shelve(self, *args, **kwargs):

~\Anaconda3\envs\tensorflow\lib\site-packages\nilearn\image\resampling.py in resample_img(img, target_affine, target_shape, interpolation, copy, order, clip)
    485     # of the target affine
    486     if xmax < 0 or ymax < 0 or zmax < 0:
--> 487         raise BoundingBoxError("The field of view given "
    488                                "by the target affine does "
    489                                "not contain any of the data")

BoundingBoxError: The field of view given by the target affine does not contain any of the data`

**Comment by poppintiger** [comment] 2018-11-26 09:06
This my raw fmri data:
[https://drive.google.com/open?id=1VXk1L0i7dP2XWYBTeRcncXe3LQ81fagd](url)

Can you help me to figure it out?

**Comment by poppintiger** [comment] 2018-11-26 09:43
I draw one slice of the raw fmri data by running:
`plotting.plot_stat_map(index_img(dataset,1) , cut_coords=[0, 0, 0])`
 it seem that the data is in MNI space.So I have no idea where is wrong?

![pretty_brain](https://user-images.githubusercontent.com/26161307/49005741-6a95d380-f1a2-11e8-8037-bc420a4308f9.png)

**Comment by poppintiger** [comment] 2018-11-26 10:07
When I select a fmri data that can be sucessufully converted to roi time series format without errors, and plot it, it show a odd image：

![pretty_brain0](https://user-images.githubusercontent.com/26161307/49007110-a0888700-f1a5-11e8-9de8-0c3d9649a29b.png)

So， I was confused so much.

**Comment by KamalakerDadi** [comment] 2018-11-26 10:22
>This my raw fmri data:
https://drive.google.com/open?id=1VXk1L0i7dP2XWYBTeRcncXe3LQ81fagd

I am unable to access it. Could you provide in another way ?

>I draw one slice of the raw fmri data by running:
plotting.plot_stat_map(index_img(dataset,1) , cut_coords=[0, 0, 0])
it seem that the data is in MNI space.So I have no idea where is wrong?

Seems good to me. Could you also check that other volumes are also at the same position i.e. AC-PC line ? Basically, you can check changing the index 1 to range of number of timepoints in your fmri data.

>When I select a fmri data that can be sucessufully converted to roi time series format without errors, and plot it, it show a odd image：

I could not understand what is this odd image representing? Is it an fMRI dataset which you want to extract timeseries on ?

**Comment by bthirion** [comment] 2018-11-26 12:09
To me the image clearly shows that your fmRI data are not in MNI space.
If you do prerprocessing with fmriprep, you might want to look at the Neurostars forum, e.g.
https://neurostars.org/t/functional-not-in-mni-space/2720/2

**Comment by poppintiger** [comment] 2018-11-27 01:40
> To me the image clearly shows that your fmRI data are not in MNI space.
> If you do prerprocessing with fmriprep, you might want to look at the Neurostars forum, e.g.
> https://neurostars.org/t/functional-not-in-mni-space/2720/2

@bthirion ,thanks so much for your reply, I will check it to see how to convert.

**Comment by NicolasGensollen** [comment] 2020-12-29 08:52
I am closing this since it is not reproducible anymore and it has been solved AFAICT. 
Feel free to re-open an issue if needed.

**Closed by NicolasGensollen** 2020-12-29 08:52 UTC
