### ISSUE TITLE
Enhancement suggestion: Have masker compute some confounds

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1241] opened 2016-08-11 17:31 UTC
Computing high-variance confounds or global signal mean is a common situation to clean data, in particular in resting-state settings.

We could add an option ('compute_confounds'), that would be one of {None, 'global_signal', 'compcor_5', 'compcor_10'} to do this during the transform in the various maskers. It would very much simplify this common usecase.

What do people think?

**Comment by banilo** [comment] 2016-08-11 17:46
+1

Especially the global-mean-regression versus not is a classical reviewer question that would be nice to have nilearn it tackled.

**Comment by GaelVaroquaux** [comment] 2016-08-11 17:52
> Especially the global-mean-regression versus not is a classical reviewer
> question that would be nice to have nilearn it tackled.

Well, I'll want compcorr more than global-mean because global mean is a
very stupid idea (makes the covariance matrix ill-conditionned by
construction), and it's a pity that the community has not realized it.

**Comment by bthirion** [comment] 2016-08-11 18:03
That makes sense. Compcor has become a standard de-facto.

**Comment by salma1601** [comment] 2016-08-11 18:10
Yes but I have always better results when I use anatomical CompCor than statistical CompCor. Sometimes removing high variance confounds gave me worse results.

**Comment by salma1601** [comment] 2016-08-11 18:11
I mean motion + statistical CompCor worse than motion

**Comment by GaelVaroquaux** [comment] 2016-08-11 18:13
> Yes but I have always better results when I use anatomical CompCor than
> statistical CompCor. Sometimes removing high variance confounds gave me
> worse results.

I agree. And that's why these things should not be on by default. But,
because they rely only on fMRI data, they are orders of magnitude easier
to use. Hence there is value to using them.

And motion + statistical compcor is not _always_ worse than only motion.
Only when the data is not very noisy.

**Comment by salma1601** [comment] 2016-08-11 18:17
>And motion + statistical compcor is not _always_ worse than only motion.

Yes I agree, but people use default things, and I would prefer they are perfect, so that we push people to have good quality data, good preprocessing pipeline. In the same spirit we push them to use mathematically rigorous estimators.
Preprocessing is very important for me, I don't like the idea of "Come on, don't car about it, with 1000 subjects we will not see the effect" ;)

I would prefer to have a possibility to enter my WM and CSF masks, and have an anatomical CompCor

**Comment by GaelVaroquaux** [comment] 2016-08-11 18:19
> I would prefer to have a possibility to enter my WM and CSF masks, and have an
> anatomical CompCor

That's much harder to do. It's not a problem that we can fix, in the
current state of things.

If BIDS preprocessed data (a standard for sharing preprocessed data)
becomes a success and is widely used, then we'll be able to tackle this
problem.

**Comment by salma1601** [comment] 2016-08-11 18:23
Ok, but then the default behaviour is important, what would you choose ? None ?

**Comment by GaelVaroquaux** [comment] 2016-08-11 18:23
> Ok, but then the default behaviour is important, what would you choose ? None ?

None.

**Comment by KamalakerDadi** [comment] 2016-08-11 20:00
>What do people think?

Do you want to do this as separate function as reported in #1104  or included in masker API ?
If it is a function, I am ready with it but needs some good wording.

**Comment by KamalakerDadi** [comment] 2016-08-11 20:05
>Do you want to do this as separate function as reported in #1104 or included in masker API ?
If it is a function, I am ready with it but needs some good wording. EDITED: I meant doc

It should not be a problem I think. we can do both ?

**Comment by GaelVaroquaux** [comment] 2016-08-11 20:08
#1104 is very useful, and should be merged, but I think that it is something different, as it does neither global signal mean, nor compcorr.

**Comment by salma1601** [comment] 2016-09-09 11:45
actually I am changing my mind: I am working with very eroded group-level WM and CSF masks, and seems to me noise is better assessed with high variance confounds than anatomical compcor.

So +1 for computing high variance confounds on the fly

**Comment by jeromedockes** [comment] 2020-05-12 14:54
possible duplicate of #104

**Comment by thomasbazeille** [comment] 2020-05-18 08:05
Maybe this could be discussed again to see whether it's something we want to integrate in the near future or not ?

**Comment by NicolasGensollen** [comment] 2021-02-23 09:29
Addressed in #2697

**Closed by NicolasGensollen** 2021-02-23 09:29 UTC
Labels: Discussion, Enhancement
