### ISSUE TITLE
Perhaps missing and/or incorrect info in nilearn.input_data.NiftiMasker

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#2635] opened 2020-12-11 20:38 UTC
Hello,
The documentation of the class `nilearn.input_data.NiftiMasker` states that the default of the arg `standardize` is "True" but in `nilearn/input_data/nifti_masker.py` line 190, it seems to be the opposite. Can someone clarify?

In addition, I'd like to confirm whether "True" <=> "zscore" for this arg; if so, perhaps, this should be better clarified in the docstring, too.

At last, the arg `standardize_confounds` is not described [here](https://nilearn.github.io/modules/generated/nilearn.input_data.NiftiMasker.html).

**Comment by NicolasGensollen** [comment] 2020-12-11 21:17
@alpinho I think this is more or less a duplicate of #2612. I'm working on it but couldn't find the time to submit a PR yet.

The documentation that you are pointing is the stable version, which does not contain `standardize_confounds` yet since this has been added very recently, after the `0.7.0` release (see #2609). The dev version is available [here](https://6381-1235740-gh.circle-artifacts.com/0/doc/_build/html/modules/generated/nilearn.input_data.NiftiMasker.html#nilearn.input_data.NiftiMasker) and should be easier to read very soon (see #2605).

The docstring seems to be up to date through:

https://github.com/nilearn/nilearn/blob/d1a2563cbf10c1470835b04bbc6e7d627d71019a/nilearn/input_data/nifti_masker.py#L94-L106

>In addition, I'd like to confirm whether "True" <=> "zscore" for this arg; if so, perhaps, this should be better clarified in the docstring, too.

Yes, `True` is equivalent to `z-score` for this argument. I agree that this is confusing and that we might want to clarify the docstring.

**Comment by alpinho** [comment] 2020-12-11 21:29
Ah!, great. Thank you very much for the quick clarification. Should I close this issue?

**Comment by NicolasGensollen** [comment] 2021-01-25 09:33
Fixed in #2649

**Closed by NicolasGensollen** 2021-01-25 09:33 UTC
Labels: Bug
