### ISSUE TITLE
File not found 'maps' when using NiftiLabelsMasker

### ISSUE THREAD

**Issue by larryzhang95** [nilearn/nilearn#2753] opened 2021-04-07 18:01 UTC
I've been trying to follow existing tutorials to apply parcellations on a new dataset where I have 4D fMRI data. This is a tutorial I have been following https://brainhack101.github.io/introML-book/01/MAIN_tutorial_intro_to_nilearn.html#visualizing-neuroimaging-volumes

However, when I perform the Masking, I get a "File Not Found: maps" error. I wonder if theres a missing dependency, or issue in the data format I am providing. 

Currently using: 
nilearn-0.7.0
Data: 
https://openneuro.org/datasets/ds000115/versions/580f8a81cce88d000a0fa730
- fmri_file refers to one of the nii.gz files in the sub-01/func/ folder.

The following is my current code and error trace: 

```
from nilearn.input_data import NiftiLabelsMasker
label_masker = NiftiLabelsMasker(labels_img=parcellation, standardize=True)
parcellation = datasets.fetch_atlas_schaefer_2018(resume=True)
fmri_matrix = label_masker.fit_transform(fmri_file)
```

Stack Trace: 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-355fd4627222> in <module>
----> 1 fmri_matrix = label_masker.fit_transform(fmri_file)

~/anaconda3/lib/python3.7/site-packages/nilearn/input_data/nifti_labels_masker.py in fit_transform(self, imgs, confounds)
    227         """ Prepare and perform signal extraction from regions.
    228         """
--> 229         return self.fit().transform(imgs, confounds=confounds)
    230 
    231     def _check_fitted(self):

~/anaconda3/lib/python3.7/site-packages/nilearn/input_data/nifti_labels_masker.py in fit(self, X, y)
    177                    _utils._repr_niimgs(self.labels_img)[:200],
    178                    verbose=self.verbose)
--> 179         self.labels_img_ = _utils.check_niimg_3d(self.labels_img)
    180         if self.mask_img is not None:
    181             logger.log("loading data from %s" %

~/anaconda3/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py in check_niimg_3d(niimg, dtype)
    314     Its application is idempotent.
    315     """
--> 316     return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
    317 
    318 

~/anaconda3/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py in check_niimg(niimg, ensure_ndim, atleast_4d, dtype, return_iterator, wildcards)
    258             return _iter_check_niimg(niimg, ensure_ndim=ensure_ndim,
    259                                      dtype=dtype)
--> 260         return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
    261 
    262     # Otherwise, it should be a filename or a SpatialImage, we load it

~/anaconda3/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py in concat_niimgs(niimgs, dtype, ensure_ndim, memory, memory_level, auto_resample, verbose)
    421     iterator, literator = itertools.tee(iter(niimgs))
    422     try:
--> 423         first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
    424     except StopIteration:
    425         raise TypeError('Cannot concatenate empty objects')

~/anaconda3/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py in check_niimg(niimg, ensure_ndim, atleast_4d, dtype, return_iterator, wildcards)
    249                 raise ValueError(message)
    250             else:
--> 251                 raise ValueError("File not found: '%s'" % niimg)
    252         elif not os.path.exists(niimg):
    253             raise ValueError("File not found: '%s'" % niimg)

```

**Comment by bthirion** [comment] 2021-04-07 21:29
Clearly the file was not found on the disk. Can you make sure  that `fmri_file` fpoints to a proper file ?

**Comment by larryzhang95** [comment] 2021-04-07 21:34
The file is definitely on the disk. I had performed the intermediate step of plotting the mean image  previously. 

The results of the code: 
![image](https://user-images.githubusercontent.com/29720526/113937617-4b65d280-97ae-11eb-9991-ac91f8e5ab95.png)

**Comment by emdupre** [comment] 2021-04-07 21:48
Hi @larryzhang95 --

The problem is that `datasets.fetch_atlas_schaefer` returns `descriptions`, `labels`, and `maps`. You seem to be expecting it to only return the equivalent of the `maps` object. You can run a working example like so:

```python
from nilearn.input_data import NiftiLabelsMasker

parcellation = datasets.fetch_atlas_schaefer_2018(resume=True)  # notice I moved this call before the masker
label_masker = NiftiLabelsMasker(labels_img=parcellation.maps, standardize=True)
fmri_matrix = label_masker.fit_transform(fmri_file)
````

In general, we use this issue tracker for bug reports or enhancement requests rather than usage questions. If you have any other follow-up questions about this example, please post on NeuroStars (https://neurostars.org) -- and feel free to refer back to this issue ! If you use the `nilearn` tag on NeuroStars, the nilearn developers will be notified of any activity there.

I'll close this conversation here, but I hope that helped answer your question !

**Closed by emdupre** 2021-04-07 21:48 UTC

**Comment by larryzhang95** [comment] 2021-04-07 21:50
Yes! This answers the question.
