### ISSUE TITLE
find_cut_slices returns repetition of the same value

### ISSUE THREAD

**Issue by duchesnay** [nilearn/nilearn#1660] opened 2018-06-15 13:31 UTC
find_cut_slices returns repetition of the same value:

```
import urllib.request
import os.path
import nibabel as nib
from nilearn import plotting

ftp_url = "ftp://ftp.cea.fr/pub/unati/people/educhesnay/images/anat_T1w.nii.gz"
urllib.request.urlretrieve(ftp_url, "anat_T1w.nii.gz")
img = nib.load("anat_T1w.nii.gz")
```

x cut is OK
```
plotting.find_cut_slices(img, direction='x', n_cuts=7, spacing='auto')
```

Probem with z cuts: all cuts are equal to 160.69490051
```
cuts = plotting.find_cut_slices(img, direction='z', n_cuts=7, spacing='auto')
print(cuts)
# [160.69490051 160.69490051 160.69490051 160.69490051 160.69490051
# 160.69490051 160.69490051]
```
The affine migth help to solve the problem
```
print(img.affine)
#[[ -1.           0.           0.         123.46980286]
# [  0.           0.           1.         -94.11079407]
# [  0.          -1.           0.         160.69490051]
# [  0.           0.           0.           1.        ]]
```

**Comment by bthirion** [comment] 2018-06-24 21:08
Yes, `coord_transform` implicitly assumes a diagonal affine, which is not the case here. Use `reorder_img`
```
cuts = plotting.find_cut_slices(reorder_img(img), direction='z', n_cuts=7, spacing='auto')
```

**Comment by KamalakerDadi** [comment] 2018-06-25 19:52
I am in favour of adding a Note section about ```reorder_img``` in find_cut_slices to fix this issue.

**Comment by bthirion** [comment] 2018-06-25 20:02
Actually, the documentation of  `coord_transform` should be revised.

**Comment by KamalakerDadi** [comment] 2018-06-25 20:04
May be both. Or use reorder_img automatically with warning message whenever an image with off-diagonal is given.

**Comment by GaelVaroquaux** [comment] 2018-06-26 09:31
> Actually, the documentation of coord_transform should be revised.

I don't see were in coord_transform there is an assumption that the
affine should be diagonal. Are you sure that the problem is there, and
not in the find_cut_slices?

**Comment by bthirion** [comment] 2018-06-26 10:03
There is the following warning in the docstring of `coord_transform`
```
Warning: The x, y and z have their output space (e.g. MNI) coordinate
ordering, not 3D numpy image ordering.
```
Which means that  the affine should be diagonal if I understand correctly ? The problem is that this function is currently called by `find_cut_slices` on non-dagonal affines and this is not caught.
Yet, I think that ideally `coord_transform` should be able to handle non-diagonal affines.

**Comment by GaelVaroquaux** [comment] 2018-06-26 17:51
> Which means that the affine should be diagonal if I understand correctly ?

No. If you look at the code of the function, it is agnostic to this.

**Comment by bthirion** [comment] 2018-06-26 20:59
Indeed, the assumption is actually made in `_transform_cut_coords`, l.188 in
https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/find_cuts.py
There is no documentation problem, since this function is not part of the public API, but it has to be called with diag affine only.

**Comment by KamalakerDadi** [comment] 2018-07-10 14:42
Closing with #1677

**Closed by KamalakerDadi** 2018-07-10 14:42 UTC
