### ISSUE TITLE
precision/covariance vs partial correlation/correlation

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1214] opened 2016-08-06 18:37 UTC
Many examples rely on covariance/inverse covariance matrices. I would prefer using their normalized versions correlation/partial correlation matrices, in particular because this avoids negating precision matrix connections. What do people think ?

**Comment by bthirion** [comment] 2016-08-06 21:18
Makes sense.

**Comment by salma1601** [comment] 2016-08-07 11:35
then I am going to make a PR to replace covariance/precision uses by correlation/partial correlation in all ROI-to-ROI connectivity examples.
@GaelVaroquaux is that OK for you ?

**Comment by GaelVaroquaux** [comment] 2016-08-08 06:15
> then I am going to make a PR to replace covariance/precision uses by
> correlation/partial correlation in all ROI-to-ROI connectivity examples.
> @GaelVaroquaux is that OK for you ?

Not really, no. It's going to make things more complex.

How exactly are you planning to do it? Maybe add a section at the end of
these example discussing this?

Can the ConnectivityMatrix estimator take this in account hidding
complexity from the user?

**Comment by AlexandreAbraham** [comment] 2016-08-08 06:52
> Can the ConnectivityMatrix estimator take this in account hidding complexity from the user?

It already does. It is just a matter of changing the `kind` parameter in ConnectivityMeasure object.

**Comment by salma1601** [comment] 2016-08-08 08:01
>Can the ConnectivityMatrix estimator take this in account hidding complexity from the user?

In fact there is a `ConnectivityMeasure(kind='partial correlation')` and `ConnectivityMeasure(kind='correlation')`. `ConnectivityMeasure` has also a parameter to handle any scikit-learn covariance estimator.
The only case which will not be handled directly is when `GroupSparseCovariance` is used: it outputs covariance and precision matrices, so in this case we need to use the functions `_corr_to_cov` and `_prec_to_partial` defined in `connectome.connectivity_matrices` module.

>How exactly are you planning to do it? Maybe add a section at the end of these example discussing this?

No, just replacing all uses of precisions and covariances by their normalized versions.

**Comment by bthirion** [comment] 2021-01-27 17:21
Duplicate of 1213 I think. Closing.

**Closed by bthirion** 2021-01-27 17:21 UTC
