### ISSUE TITLE
 Code refactoring necessary for future ease of maintenance and development

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1769] opened 2018-10-02 11:56 UTC
Also for Nistats: https://github.com/nistats/nistats/issues/239
There are many functions in Nilearn that are super long, some as much as ~100 lines and do multiple things within the same function body.
There are many difficulties with such an approach. It makes it impossible to do Test-Driven Development, the recommended way of programming. It also means new functions have to work around existing functionality, which can not be segregated from existing functions due to this reason.

In the long-term, this code will become increasingly fragile and difficult to maintain. It also sends the message to new contributors and for contributions that this is an acceptable way to write new code.

As a rule of software engineering, each function should do one, and ONLY one thing. In python, this usually means 5-7 lines in a function. So instead of a 100 line function, we should (for example), have 20 functions around 5 lines each. All called by an encompassing function.

This also ensures we can write more atomic unit tests for each of those small functions.

I intend to start refactoring this code. This is a massive undertaking, so I will do this slowly and piecemeal, while adding more atomic unit tests.

This is in line with industry standard clean code principles for improving code quality and something I intend to do simultaneously where ever I see code that is difficult to comprehend.

**Comment by tsalo** [comment] 2022-04-18 17:51
Since this is a duplicate of #2383 (now that nistats has been merged in), can we close it?

**Comment by jeromedockes** [comment] 2022-04-18 19:06
sure! Also, while I agree that very long functions are often harder to maintain and more likely to contain bugs, I think we should be wary of making big changes to code that is working well for the sake of style. there is a very real risk of introducing bugs, and also of spending a lot of time to end up with something that is not that much better than the original version. This is especially true for older parts of the codebase. They sometimes look a bit more messy, but they have been in the hands of users who file bug reports for a long time, and that is something very valuable that unit tests, while very useful, cannot replace. Rather than doing it systematically, I am more in favor of doing the refactoring when necessary, for code that needs to be changed anyway when introducing new features (or fixing bugs), for example as @NicolasGensollen  did when adding the plotly backend to surface plotting functions.

**Comment by tsalo** [comment] 2022-04-18 19:20
That's a really good point. Perhaps we can add something to the contributing documentation about writing new code in small functions, but avoiding large refactors for the sake of enforcing this style?

**Comment by jeromedockes** [comment] 2022-04-18 19:21
> As a rule of software engineering, each function should do one, and ONLY one thing. In python, this usually means 5-7 lines in a function. So instead of a 100 line function, we should (for example), have 20 functions around 5 lines each. All called by an encompassing function.

but then wouldn't the encompassing function have at least 20 > 7 lines? :D . I'm joking and I do agree that bugs tend to creep in as soon as a function doesn't fit on a screen, but I also think that some variability in contributors' programming style and personal taste is acceptable (I think many would set the limit higher than 5-7 lines / function), and that deviations from general guidelines are sometimes warranted. What is "clean code" and what is "difficult to comprehend" will vary a lot from one programmer to the next

**Comment by jeromedockes** [comment] 2022-04-18 19:24
> Perhaps we can add something to the contributing documentation about writing new code in small functions, but avoiding large refactors for the sake of enforcing this style?

Yes I like this idea. I think we already have something about avoiding changes that are not directly related to the task at hand (meaning discussed in the issue linked to the PR), we could expand that section a bit, and expand the section where we discuss unit tests to say that short, simple functions are usually easier to understand and unit-test

**Closed** 2022-04-18 21:39 UTC
Labels: code quality, Maintenance
