### ISSUE TITLE
Using `plotting.plot_img_on_surf` with the `threshold` option seems to produce a slight asymmetry in colorbar

### ISSUE THREAD

**Issue by shawnrhoads** [nilearn/nilearn#3123] opened 2022-01-11 04:44 UTC
Using `plotting.plot_img_on_surf` with the `threshold` option seems to produce a slight asymmetry in colorbar.

This is especially noticeable for small thresholds. For example, the following code (with `threshold=.03`) produces an output with a colorbar that doesn't seem centered around zero (middle tick mark is positioned more to the right).

```python
import nibabel as nib
from nilearn import plotting

stat_img = nib.load('example.nii.gz')
plotting.plot_img_on_surf(stat_img,
                          views=['lateral', 'medial'],
                          hemispheres=['left', 'right'],
                          threshold=.03,
                          cmap='blue_orange',
                          colorbar=True)
```
![example](https://user-images.githubusercontent.com/24925845/148875680-ad63b3ad-be68-4f6e-ac1f-7d106502eb13.jpg)

Any suggestions on how to remedy this in the short-term? Seems like it could be a font/line width issue (instead of the bar actually being asymmetric). For example, is there an easy to way to remove the middle tick mark indicating zero?

**Comment by jeromedockes** [comment] 2022-01-11 15:35
Hi, there may be a difference of 1/256th of the length of the colorbar because the colormap is discrete https://github.com/nilearn/nilearn/blob/d43e4ff0e150634c474f834d523ada1529d218d1/nilearn/plotting/surf_plotting.py#L1109), or it might just be the thickness of the tick as you say. could you share "example.nii.gz" ? but I would bet this will be a "wontfix"

the function returns a tuple fig, axes. the second element is a list of all the axes it created, the last of which is the colorbar -- we are working on improving the interface and documentation of these functions.
So you can just grab the tick line and hide it:

```python
from nilearn import plotting, datasets

stat_img = datasets.fetch_neurovault_motor_task()["images"][0]
fig, axes = plotting.plot_img_on_surf(
    stat_img,
    views=["lateral", "medial"],
    hemispheres=["left", "right"],
    threshold=0.03,
    cmap="blue_orange",
    colorbar=True,
)
# draw the figure so tick lines get placed in their positions
fig.draw(fig.canvas.get_renderer())
ax = axes[-1]
for line in ax.get_xticklines():
    # get lines corresponding to the tick at 0. (the top one is actually
    # already not visible)
    if line.get_xdata()[0] == 0.:
        line.set_visible(False)
plotting.show()
```

**Comment by shawnrhoads** [comment] 2022-01-11 16:11
This sounds fine! Here is the [example.nii.gz](https://github.com/nilearn/nilearn/files/7848091/example.nii.gz) file.

Your code snippet is a good enough remedy for me. Thanks a bunch!!

**Comment by jeromedockes** [comment] 2022-01-11 16:59
thanks! having the image is useful to reproduce the problem.
so to summarize, the cmap could be made a bit more symmetric by taking the next integer here rather than truncating:
https://github.com/nilearn/nilearn/blob/d43e4ff0e150634c474f834d523ada1529d218d1/nilearn/plotting/surf_plotting.py#L1110

```diff
modified   nilearn/plotting/js_plotting_utils.py
@@ -99,7 +99,7 @@ def colorscale(cmap, values, threshold=None, symmetric_cmap=True,
     if threshold is not None:
         abs_threshold = check_threshold(threshold, values, fast_abs_percentile)
         istart = int(norm(-abs_threshold, clip=True) * (cmap.N - 1))
-        istop = int(norm(abs_threshold, clip=True) * (cmap.N - 1))
+        istop = int(np.ceil(norm(abs_threshold, clip=True) * (cmap.N - 1)))
         for i in range(istart, istop):
             cmaplist[i] = (0.5, 0.5, 0.5, 1.)  # just an average gray color
     our_cmap = mpl.colors.LinearSegmentedColormap.from_list(
```

similar snippets of code are copied in several places in the codebase and would need to be fixed as well, eg [here](https://github.com/nilearn/nilearn/blob/d43e4ff0e150634c474f834d523ada1529d218d1/nilearn/plotting/surf_plotting.py#L353) and [here](https://github.com/nilearn/nilearn/blob/d43e4ff0e150634c474f834d523ada1529d218d1/nilearn/plotting/displays/_slicers.py#L448)

@NicolasGensollen  WDYT?

also it is probably worth seeing if these duplicated pieces of code can be refactored

**Comment by jeromedockes** [comment] 2023-01-26 14:58
I think the slight asymmetry isn't a big deal for most users, so I'll close this as a "won't fix" for now; and there is always the option of removing the center tick as mentioned above

**Closed by jeromedockes** 2023-01-26 14:58 UTC
Labels: Bug, Plotting, Good first issue, impact: low, effort: low, priority: low
