### ISSUE TITLE
could display.add_contours error when no contour found be replaced with warning ?

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1441] opened 2017-04-19 13:21 UTC
My code is often breaking because there is no contours are found for the default cut
```Python
display = plotting.plot_anat(anat_filename,
                             title='binary masks contours on top of anat')
display.add_contours(csf_mask_img, colors='c')
```
>ValueError: zero-size array to reduction operation minimum which has no identity

May be we can catch this error and simply replace it by a warning ? For instance, I use ROIs contours on top of my stat map plot but I don't want it to break just because of this visualization issue. What do you think ?

**Comment by GaelVaroquaux** [comment] 2017-04-19 13:26
+1: to error imposes a lot of error managment for little benefits.

**Comment by KamalakerDadi** [comment] 2017-05-29 21:20
Hi @salma1601 Could you test this FIX from this PR #1459 . I some how hope that it should fix. 
You should see something like this if it could able to find mask (contour) to overlay.
```python
nilearn/plotting/displays.py:670: UserWarning: empty mask
  get_mask_bounds(new_img_like(img, not_mask, affine))
```

**Comment by salma1601** [comment] 2017-05-30 10:13
Hi ! no sorry it didn't fix it.

**Comment by poquirion** [comment] 2017-11-16 15:37
I can't reproduce, but I tried with an empty mask. And got a warning, no error.

**Comment by KamalakerDadi** [comment] 2017-11-16 15:41
I was hoping that it should be fixed with PR #1459 . Is it the same warning you got as I asked in the thread ?

**Comment by poquirion** [comment] 2017-11-16 15:45
Gaël is sitting to my left and recommend the the issue be closed... I guess it is fixed.

**Comment by KamalakerDadi** [comment] 2017-11-16 15:52
>Gaël is sitting to my left and recommend the the issue be closed... I guess it is fixed.

Ok closing then. Thanks

**Closed by KamalakerDadi** 2017-11-16 15:52 UTC
Labels: Enhancement, Good first issue

**Comment by GaelVaroquaux** [comment] 2017-11-16 16:24
Great! One issue closed
