### ISSUE TITLE
Caching of extraction_function in filter_and_extract is constantly invalidated

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#767] opened 2015-08-24 15:50 UTC
In `base_masker.py`, line 96 :
```python
    region_signals, aux = cache(extraction_function, memory,
                                func_memory_level=2,
                                memory_level=memory_level)(imgs)
```
leads to the caching of a function `unknown`, with warning : 
```
/volatile/arthur/work/repos/nilearn/nilearn/input_data/base_masker.py:98: JobLibCollisionWarning: Cannot detect name collisions for function 'unknown'
  memory_level=memory_level)(imgs)
WARNING:root:[MemorizedFunc(func=<nilearn.input_data.nifti_masker._ExtractionFunctor object at 0x7f1500c5b5d0>, cachedir='nilearn_cache/joblib')]: Clearing cache nilearn_cache/joblib/nilearn/input_data/nifti_masker/unknown
```

**Comment by AlexandreAbraham** [comment] 2015-08-24 16:09
Good catch ;). I'll have to catch my bus soon so I'll fix it later. It's not a big deal, I already know how to do it, don't bother looking for the solution.

**Comment by AlexandreAbraham** [comment] 2015-08-24 22:27
Can you check that the problem is fixed?

**Comment by arthurmensch** [comment] 2015-08-25 16:28
Yes, `unknown` is now `nifti_masker_extractor`

**Comment by AlexandreAbraham** [comment] 2015-08-25 16:38
Cool! closing.

**Closed by AlexandreAbraham** 2015-08-25 16:38 UTC
