### ISSUE TITLE
View does not match output when plotting surfaces

### ISSUE THREAD

**Issue by Rahul-Brito** [nilearn/nilearn#3782] opened 2023-06-27 17:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

Linux Centos7

### Python version

- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.0

### Expected behavior

When I plot my surface data and set `view = 'medial'` I still get the lateral view. This happens even if I also set `hemi='right'` or `hemi='left'`.  Code below.

When I try to set `view=(0.0, -180.0)`, I also don't get the medial view, but get an error (see below).

### Current behavior & error messages

I expect it to plot the medial view (e.g. I want to see cingulate cortex, but I get the lateral view when I set `view=medial`

When I set 'view=(0.0, -180.0)', I get this error:

`ValueError: view must be one of ('anterior', 'posterior', 'medial', 'lateral', 'dorsal', 'ventral')`

### Steps and code to reproduce bug

`z_second_level_betas` is a 91k element np array from a cifti file (a surface mesh). 

```
from nilearn import plotting as nplot

nplot.plot_surf_stat_map(
    hcp.mesh.inflated, hcp.cortex_data(z_second_level_betas), view='medial', #threshold=threshold,
    symmetric_cbar = False,
    colorbar=True,
    bg_map=hcp.mesh.sulc)
```

**Comment by Remi-Gau** [comment] 2023-06-27 20:04
I have trimmed down the code from one of the example to try to reproduce your bug:

```python
from nilearn import datasets
from nilearn import plotting
from nilearn import surface

import numpy as np
import numpy as np

from scipy import stats

nki_dataset = datasets.fetch_surf_nki_enhanced(n_subjects=1)

destrieux_atlas = datasets.fetch_atlas_surf_destrieux()
parcellation = destrieux_atlas['map_left']
labels = destrieux_atlas['labels']

pcc_region = b'G_cingul-Post-dorsal'
pcc_labels = np.where(parcellation == labels.index(pcc_region))[0]
timeseries = surface.load_surf_data(nki_dataset['func_left'][0])
seed_timeseries = np.mean(timeseries[pcc_labels], axis=0)

stat_map = np.zeros(timeseries.shape[0])
for i in range(timeseries.shape[0]):
    stat_map[i] = stats.pearsonr(seed_timeseries, timeseries[i])[0]
stat_map[np.where(np.mean(timeseries, axis=1) == 0)] = 0

fsaverage = datasets.fetch_surf_fsaverage()

plotting.plot_surf_stat_map(fsaverage['pial_left'], stat_map=stat_map,
                            hemi='left', view='medial', colorbar=True,
                            bg_map=fsaverage['sulc_left'], bg_on_data=True,
                            darkness=.3, title='Correlation map')

plotting.show()                            

plotting.plot_surf_stat_map(fsaverage['pial_left'], stat_map=stat_map,
                            hemi='left', view='lateral', colorbar=True,
                            bg_map=fsaverage['sulc_left'], bg_on_data=True,
                            darkness=.3, title='Correlation map')

plotting.show()     
```

I get what would be expected: meaning I cannot reproduce your bug.

Can you try to run this code to see if you still get this problem with it?

**Comment by Rahul-Brito** [comment] 2023-06-27 20:32
Thank you @Remi-Gau! I ran that code in my environment and it works as expected. I will try to see what is going wrong on my end, thank you!

**Comment by Rahul-Brito** [comment] 2023-06-27 21:11
Looks like I had to specific just left cortex for my surface mesh and stat map and bg map like you did in your example so that I only was giving the function the vertices from the left hemisphere (see below). Thank you!

A question - should it be expected to work if you have it a full brain surface mesh and stat map? I wonder if this has to do with differences in GIFTI (which I have not used) and CIFTI. It looks like in `fsaverage` above, you have to specify which mesh you are using e.g. `'pial_left` for the plotting function, since of course if you just give it `fsaverage` it sees the Bunch.

What worked for me:
`nplot.plot_surf_stat_map(
    hcp.mesh.inflated_left, hcp.left_cortex_data(z_second_level_betas), views= 'medial',
    hemi='right', #threshold=threshold,
    symmetric_cbar = False,
    colorbar=True,
    bg_map=hcp.mesh.sulc_left)`

**Comment by Rahul-Brito** [comment] 2023-07-21 16:57
Me and @ymzayek and @emdupre talked about this at brainhack 2023 more. To better explain, I am using the 91k fsLR space with my cifti (as that is what I get "by default" from fmriprep when i use the `-cifti-outputs`) and then the hcp-utils helper functions (https://rmldj.github.io/hcp-utils/).

hcp-utils has suface meshes that include both hemispheres e.g. 

`import hcp_utils as hcp

hcp.mesh.inflated
`

The below works to give me the left medial cortex, as described above (though above I used 'views' and a parameter instead of 'view'

'
# betas['intercept'] is a pandas series with shape (91282,) that represents the second level beta values per greyordinate

nplot.plot_surf_stat_map(
    hcp.mesh.inflated_left, hcp.left_cortex_data(betas['intercept']), view= 'medial', hemi='left', 
    symmetric_cbar = False,
    colorbar=True,
    title_font_size=30,
    bg_map=hcp.mesh.sulc_left)

nplot.show()' 

What I expected to work was the below code. basically I want to use `hcp.mesh.inflated` as my surface mesj since it represents both hemispheres, and then specify both the hemisphere and view to get left medial cortex. However, when I run this I get the right lateral hemisphere:

`nplot.plot_surf_stat_map(
    hcp.mesh.inflated, hcp.cortex_data(betas['intercept']), view='medial', hemi='left', #threshold=3.5,
    symmetric_cbar = False,
    colorbar=True,
    bg_map=hcp.mesh.sulc)

nplot.show()`

We are still digging, and did some digging. At least at a high level, it looks like `hcp.mesh.inflated` is a tuple,; hcp.mesh.inflated[0]` has a shape (64984, 3), which seems to fit the number of greyordinates expected in the full cortext, but hcp.mesh.inflated[1]` has a shape (129960, 3) which is twice as long and we aren't sure why.

The other weird thing is that `hcp.struct.cortex` which should show the indices of all the structures (cortex, subcortical) has a length of 0 to 59412, which is less than the 64k above.

**Comment by Remi-Gau** [comment] 2024-11-21 13:10
will close this as the original issue is 'solved'

later comments I think will get addressed in the near future as we expand how the new SurfaceImage format interacts with other type surface data formats.

**Closed by Remi-Gau** 2024-11-21 13:10 UTC
Labels: Usage, Surface
