### ISSUE TITLE
[DOC] Formatting of docstring in regions.Parcellations

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#3914] opened 2023-08-14 20:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Right now, the line break in the docstring for `nilearn.regions.Parcellations` is causing sub-optimal formatting.

Here's the rendered docstring
<img width="697" alt="Screenshot 2023-08-07 at 20 20 56" src="https://github.com/nilearn/nilearn/assets/15017191/8ac3cca4-5ccc-4235-a086-c4276527a7b4">

and the accompanying docstring:
https://github.com/nilearn/nilearn/blob/321494420f95c7a5e2172108400194b37a02e628/nilearn/regions/parcellations.py#L135-L136

As you can see, "hierarchical_kmeans" is not formatted in the same styling as the other valid methods.

### List any pages that would be impacted.

https://nilearn.github.io/stable/modules/generated/nilearn.regions.Parcellations.html#nilearn.regions.Parcellations

**Comment by Remi-Gau** [comment] 2023-08-17 12:43
I was thinking: as this is not mission critical we should probably keep it for someone who wants to do a first contribution, no?

**Comment by ymzayek** [comment] 2023-08-17 13:10
Sure! it already has the good first issue label :)

**Comment by NIkhilgKrish** [comment] 2023-10-09 09:18
Has this issues been merged or is there an existing pull request? If not can I pick it up as a good first issue

**Comment by Remi-Gau** [comment] 2023-10-09 09:19
@NIkhilgKrish 

it is all yours for the taking if you want it. 😃

**Comment by NIkhilgKrish** [comment] 2023-10-10 07:19
Found a couple of bugs when going through issue:
1. Matplotlib seems to have updated to 3.8 this September. This is what observed to have caused the sphinx doc generation to encounter an extension error
`Could not import extension sphinxext.opengraph (exception: cannot import name 'pyplot' from 'matplotlib' (unknown location))`

     Temporary fix is to downgrade matplotlib in venv to 3.7.

2. On running the test the unchanged code fails for
`nilearn.regions.tests.test_parcellations::test_parcellations_no_warnings`

**Comment by ymzayek** [comment] 2023-10-10 09:07
Hi @NIkhilgKrish it is hard to tell where these bugs come from. It would be best if you open a pull request with a fix for the specific formatting issue reported here and our CI should catch any errors caused by changes resulting from the fix. If the bugs you are describing are not related to this issue or to code changes fixing this issue then they should be reported in a new issue with a description and code to reproduce the issue.

For this issue I suggest to start by just adding a backslash to the end of this line:
    https://github.com/nilearn/nilearn/blob/960589c05b6a63ed612f2feb749ee4472e5aa43f/nilearn/regions/parcellations.py#L136C11-L136C11

Open a pull request and from there we will help you finish the fix with no failures through our review process. Have a look at our [contributing guidelines](https://nilearn.github.io/stable/development.html#contribution-guidelines) to help you get a better idea of our development process.

**Comment by NIkhilgKrish** [comment] 2023-10-10 11:02
Sure! I have created the pull request with just the base issue for now. Will report the other bug later.

**Closed** 2023-10-19 08:18 UTC
Labels: Documentation, Good first issue
