### ISSUE TITLE
Problem with NITRC servers 

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2334] opened 2020-03-12 10:42 UTC
Attempting to download from them is giving a 403 forbidden error.
Have contacted them for update/fix.

There may be other servers affected as well.

**Comment by emdupre** [comment] 2020-03-12 13:54
I started looking into this yesterday and didn't get a chance to write back, sorry !

It sounds likely that the servers have updated their internal `mod_security` (or a similar config) and are now blocking requests from known bots like those originating from urllib. The most consistent way around this is to spoof the browser, using something [like this described answer](https://stackoverflow.com/a/16627277).

We could update our `fetch_files` utility function accordingly, if that seems reasonable to everyone.

**Comment by emdupre** [comment] 2020-03-12 14:12
Just to say explicitly: Spoofing the browser isn't great on the receiving server, so it's not something we should do if we have another alternative. Would be curious to know what you hear back, @kchawla-pi !

**Comment by kchawla-pi** [comment] 2020-03-12 14:14
That can't be all of it. I tried accessing those URLs via the browser and show a red exclamation mark after loading the site.

**Comment by kchawla-pi** [comment] 2020-03-12 14:14
Thanks @emdupre for investigating this.

**Comment by jeromedockes** [comment] 2020-03-12 14:48
> so it's not something we should do

I agree, let's just wait for an answer from nitrc. @kchawla-pi  keep us posted!

**Comment by jeromedockes** [comment] 2020-03-12 14:51
Interestingly I am not able to reproduce: does the following script fail for you @kchawla-pi and @emdupre ?
```python
from nilearn import datasets

haxby = datasets.fetch_haxby()
sample = datasets.fetch_oasis_vbm(n_subjects=1)
```

It seems that @deepakkochhar11 was receiving 403 responses to requests from his own machine

**Comment by kchawla-pi** [comment] 2020-03-12 14:52
I am able to reproduce this.

**Comment by kchawla-pi** [comment] 2020-03-12 14:54
@jeromedockes could that be because you already have the data downloaded? Try specifying a new directory.

**Comment by emdupre** [comment] 2020-03-12 14:55
That works for me ! I wasn't aware of failures on (and so didn't check) `datasets.fetch_oasis_vbm(n_subjects=1)` yesterday, but I can confirm that `datasets.fetch_haxby()` was failing with a local 403 error.

Want to restart one of the CircleCI jobs, @kchawla-pi, to confirm ?

**Comment by deepakkochhar11** [comment] 2020-03-12 14:58
Hi @emdupre 

I agree with you. I checked `datasets.fetch_oasis_vbm(n_subjects=1)` yesterday and it was working fine but it is not working today. 

@jeromedockes I tried it both on my local machine and Google Colab but I still got 403 error. The same code was working until yesterday.

**Comment by kchawla-pi** [comment] 2020-03-12 14:59
> Want to restart one of the CircleCI jobs, @kchawla-pi, to confirm ?

Groundhog Day!

**Comment by jeromedockes** [comment] 2020-03-12 15:00
> @jeromedockes could that be because you already have the data downloaded? Try specifying a new directory.
No, it gets downloaded

**Comment by jeromedockes** [comment] 2020-03-12 15:12
> I am able to reproduce this.
sorry I am a bit confused: all nitrc datasets e.g. `fetch_haxby` are currently failing for you @kchawla-pi , and succeeding for @emdupre ?

all fetchers seem to succeed for me

**Comment by kchawla-pi** [comment] 2020-03-12 15:21
> sorry I am a bit confused: 

```python
from nilearn.datasets import fetch_haxby, fetch_oasis_vbm


haxby_data = fetch_haxby(data_dir='~/Desktop/haxby')
oasis_data = fetch_oasis_vbm(data_dir='~/Desktop/oasis')
```
This script of mine fails with 403 error. The mask url in haxby, saved on NITRC is the one that fails.

**Comment by kchawla-pi** [comment] 2020-03-12 15:23
> all fetchers seem to succeed for me

Check out the recent CircleCI builds. I am certain Travis and Azure are failing as well.

**Comment by jeromedockes** [comment] 2020-03-12 15:33
> This script of mine fails with 403 error. The mask url in haxby, saved on NITRC is the one that fails.

the download succeeds for me. is it possible that some IP addresses got blacklisted?

**Comment by deepakkochhar11** [comment] 2020-03-12 15:40
I just ran this code and it is working for me now. No 403 Forbidden error this time.

```
from nilearn import datasets
n_subjects = 416
oasis_dataset = datasets.fetch_oasis_vbm(n_subjects=n_subjects)
```

Why did this happen? 

Is it because of the change in download URLs or IP addresses being blocked owing to the repeated posting of requests to fetch data?

@kchawla-pi @emdupre @jeromedockes

**Comment by jeromedockes** [comment] 2020-03-12 16:00
> Why did this happen? 
>
> Is it because of the change in download URLs or IP addresses being blocked owing to the repeated posting of requests to fetch data?
>
> @kchawla-pi @emdupre @jeromedockes  

the urls used by nilearn are still the same. It is possible that nitrc
has a list of blacklisted IPs that get cleared after a while but I
really don't know.

BTW can someone who manages to reproduce the error post the full
response? (not just the status code)

**Comment by kchawla-pi** [comment] 2020-03-12 16:06
My script is working now.

**Comment by emdupre** [comment] 2020-03-12 16:14
403 errors can be intermittent. I'll keep :crossed_fingers: that it's resolved permanently, but it's possible this could come back in the next few days. I think the CI infrastructure will be the best way to test it continuously.

@jeromedockes I don't have the full stacktrace any more, but when I was looking at `fetch_haxby` yesterday, the error specifically originated at this line: https://github.com/nilearn/nilearn/blob/cc22775122dca01beda90626d63018dc4c82de38/nilearn/datasets/func.py#L102

and traced through to here:

https://github.com/nilearn/nilearn/blob/cc22775122dca01beda90626d63018dc4c82de38/nilearn/datasets/utils.py#L582

**Comment by jeromedockes** [comment] 2020-03-12 16:32
> @jeromedockes I don't have the full stacktrace any more, but when I was looking at `fetch_haxby` yesterday, the error specifically originated at this line: https://github.com/nilearn/nilearn/blob/cc22775122dca01beda90626d63018dc4c82de38/nilearn/datasets/func.py#L102
>
> and traced through to here:
>
> https://github.com/nilearn/nilearn/blob/cc22775122dca01beda90626d63018dc4c82de38/nilearn/datasets/utils.py#L582
>

thanks! rather than the traceback I meant the HTTP response.
but if the problem disappeared that's fine. Still it would be nice to
hear from the NITRC administrators; maybe we're doing something wrong

**Comment by kchawla-pi** [comment] 2020-03-13 11:31
@emdupre was correct. They went a little overboard blocking DOS attacks. Seems fixed now.

**Comment by jeromedockes** [comment] 2020-03-16 17:45
so can we close this?

**Comment by kchawla-pi** [comment] 2020-03-16 17:48
Yeah

**Closed** 2020-03-16 17:59 UTC
