### ISSUE TITLE
Hemisphere plotting

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#801] opened 2015-10-21 12:56 UTC
Some neuropeople asked me why we were only plotting the right hemisphere in nilearn. In fact, in our plotting functions, in the sagittal view, the brain is "looking to" the right, which means that this is a right hemisphere to neuropeople. We probably want to flip it when the slice is in the left part of the brain in plotting and make two sagittal plots (one left hemisphere and one right hemisphere) in the glass brain.

**Comment by rschmaelzle** [comment] 2016-02-08 16:45
Hi, that is indeed something I would find handy. Is there perhaps an interim solution? I tried playing with gca.invert_xaxis() but did not succeed. Best, Ralf.

**Comment by lesteve** [comment] 2016-02-08 22:50
This is a duplicate of #942, right ?

**Comment by GaelVaroquaux** [comment] 2016-02-08 22:54
Indeed, it's a duplicate.

Also,  @rschmaelzle : there is no quick workaround

**Closed by GaelVaroquaux** 2016-02-08 22:54 UTC
Labels: Enhancement, Plotting
