### ISSUE TITLE
3 bugs in resample_img

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#322] opened 2014-12-17 09:39 UTC
Working with HCP resting-state data, it seems I have encountered three potentially new bugs using resample_img:

a) using input images that have bad affines can cause segmentation faults, quitting python directly

b) using interpolation=nearest can cause "completely messed up" niftis, similar to the recent resample_img bug related to endianess

c) comparing 4d niftis before and after resampling in FSLView, in one case, turned out to look fine for the first 500 images, yet resulted in rather different histogramms in images in the second 500 volumes

I will try to provide python scripts reproducing these things and the corresponding data.

**Comment by AlexandreAbraham** [comment] 2015-01-07 11:56
I can't download the data.

**Comment by banilo** [comment] 2015-01-07 12:04
Smells like a dropbox-access issue.

**Comment by AlexandreAbraham** [comment] 2015-01-07 12:30
Using the code you posted, I have a bounding box issue (part of the cerebellum is cut). Apart from that, both files are identical.

**Comment by lesteve** [comment] 2015-01-09 10:15
I moved the segmentation fault one to #346.

**Comment by AlexandreAbraham** [comment] 2015-01-11 22:29
2 other bugs are:
* the brain is cropped during resampling
* data is very different from original after resampling: this is due to a bug in FSLview on Mac OS X

**Comment by lesteve** [comment] 2015-01-12 14:10
Should we close this one then?

**Comment by AlexandreAbraham** [comment] 2015-01-14 00:18
I can't reproduce the cropping bug. I close this one, let's open other issues with precise examples if the problem comes up again.

**Closed by AlexandreAbraham** 2015-01-14 00:18 UTC
Labels: Bug
