### ISSUE TITLE
vol_to_surf inmproperly transforms data

### ISSUE THREAD

**Issue by magdalenasabat** [nilearn/nilearn#3326] opened 2022-08-04 16:33 UTC
I'm trying to draw roi on fsaverage surface based on Glasser parcellation (from : https://github.com/neurodata/neuroparc/atlases/label/Human/Glasser_space-MNI152NLin6_res-1x1x1.nii.gz). The transformed img is too small (?). 

Nilearn version: latest

### Expected behavior
Works more or less correctly before the transform
```
from nilearn import  surface, datasets
from nilearn.image import  load_img
from nilearn.plotting import plot_surf_roi,plot_roi

glasser_rois = load_img('Glasser_space-MNI152NLin6_res-1x1x1.nii.gz' )


plot_roi( glasser_rois, display_mode='mosaic', 
        black_bg=False,
        cmap='gist_ncar', 
        view_type = 'contours'
    )
```
![image](https://user-images.githubusercontent.com/55433393/182895235-30865672-1e83-46d0-b8e9-af82300210cf.png)

when trying to project to surface the parcelattion seems too small?.

```
fsaverage = datasets.fetch_surf_fsaverage('fsaverage')

glasser_rois_surf = surface.vol_to_surf(glasser_rois,fsaverage['infl_left'] )

plot_surf_roi( fsaverage['infl_left'],glasser_rois_surf,        
        cmap='gist_ncar', 
        view='lateral',
        bg_map=fsaverage['sulc_left'], 
        bg_on_data=True,)
```
![image](https://user-images.githubusercontent.com/55433393/182895542-b2c4d9c2-5e02-4bb1-8bbf-6b5de2bcde4f.png)

[Glasser_space-MNI152NLin6_res-4x4x4.nii.gz](https://github.com/nilearn/nilearn/files/9261334/Glasser_space-MNI152NLin6_res-4x4x4.nii.gz)
[Glasser_space-MNI152NLin6_res-2x2x2.nii.gz](https://github.com/nilearn/nilearn/files/9261335/Glasser_space-MNI152NLin6_res-2x2x2.nii.gz)
[Glasser_space-MNI152NLin6_res-1x1x1.nii.gz](https://github.com/nilearn/nilearn/files/9261336/Glasser_space-MNI152NLin6_res-1x1x1.nii.gz)

**Comment by jeromedockes** [comment] 2022-08-04 18:18
Thanks for this nice summary, @kchawla-pi! I think it would be better if we
reached a decision (at least in principle) before you do the actual work of
writing the configuration files and opening the PR, to avoid wasting your time
if we eventually decide not to automate formatting.

**Comment by jeromedockes** [comment] 2022-08-04 19:03
to help use this function we could add an Examples section to the docstring? also I think we can get rid of the warning that it is experimental, I don't think that is the case any more

**Comment by bthirion** [comment] 2022-08-04 19:19
There exist already a bunch of examples (see https://nilearn.github.io/stable/modules/generated/nilearn.surface.vol_to_surf.html) I don't see what to add.

**Comment by jeromedockes** [comment] 2022-08-04 19:33
I was thinking of a tiny example in the docstring itself (not an example
in the gallery).

something like
```
Examples
--------
 >>> from nilearn import datasets, surface
 >>>
 >>> fsaverage = datasets.fetch_surf_fsaverage("fsaverage5")
 >>> img = datasets.fetch_neurovault_motor_task()["images"][0]
 >>> surf_data = surface.vol_to_surf(
 ...     img, surf_mesh=fsaverage.pial_left, inner_mesh=fsaverage.white_left
 ...  )
```

But if it's not necessary then I think we can close
this issue.

**Comment by bthirion** [comment] 2022-08-05 06:49
Why not, though I don't think it addresses the concern raised in this issue.

**Comment by magdalenasabat** [comment] 2022-08-06 10:17
Well I feel like a dummy for not knowing the representation space of the two pial and surface projections (probably because I did not work enough with either). I imagined that it should be possible to project to the inflated directly. For a newbie like me a function _.vol_to_surf_ sort of suggests that you can project to either inflated or pial as both are surface representations. Maybe an explicit comment along the line: 'use pial coordinates to project to surface representation' could be helpful?

**Comment by jeromedockes** [comment] 2022-08-16 10:30
Sorry for the late reply @magdalenasabat. Don't feel like a dummy! :D certainly
the documentation can be improved. I think the confusion comes from the term
"projection". The transformation is not a projection; image values are sampled
at each node's position as explained in [this example](https://nilearn.github.io/stable/auto_examples/01_plotting/plot_surface_projection_strategies.html).

The inflated surface does not correspond to anything real -- the mesh is
deformed, moving the nodes' positions well outside of the actual cortex, so that
the mesh can be visualized more easily. But sampling the image at these
positions does not make sense as they are not on the cortex's surface anymore.
Therefore the inflated (and sphere) surfaces are just used for plotting, but
never for sampling the signal.

**Comment by jeromedockes** [comment] 2022-09-09 16:47
I think we can close this as the problem is fixed by using the non-inflated surfaces. @magdalenasabat don't hesitate to re-open if necessary or to ask more questions here or on neurostars!

**Closed by jeromedockes** 2022-09-09 16:47 UTC
Labels: Documentation
