### ISSUE TITLE
make_thumbnials function of gen_rst.py not fault-tolerant enough

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#671] opened 2015-07-15 08:19 UTC
This following fault happens, and the whole "make doc" process halts.  We should catch errors in line 320 return.

# Sphinx version: 1.2.2
# Python version: 2.7.6
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 139, in __init__
    self._init_builder(buildername)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 201, in _init_builder
    self.emit('builder-inited')
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 400, in emit
    results.append(callback(self, *args))
  File "/home/parietal/dohmatob/CODE/FORKED/nilearn/doc/sphinxext/sphinxgallery/gen_gallery.py", line 51, in generate_gallery_rst
    generate_dir_rst(directory, fhindex, examples_dir, gallery_dir, gallery_conf, plot_gallery, seen_backrefs)
  File "/home/parietal/dohmatob/CODE/FORKED/nilearn/doc/sphinxext/sphinxgallery/gen_rst.py", line 277, in generate_dir_rst
    backrefs = generate_file_rst(fname, target_dir, src_dir, gallery_conf, plot_gallery)
  File "/home/parietal/dohmatob/CODE/FORKED/nilearn/doc/sphinxext/sphinxgallery/gen_rst.py", line 570, in generate_file_rst
    make_thumbnail(first_image_file, thumb_file, 400, 280)
  File "/home/parietal/dohmatob/CODE/FORKED/nilearn/doc/sphinxext/sphinxgallery/gen_rst.py", line 320, in make_thumbnail
    img = Image.open(in_fname)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2028, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

**Comment by AlexandreAbraham** [comment] 2015-07-15 08:23
This is a sphinxgallery problem, not a nilearn one. Closing.

**Closed by AlexandreAbraham** 2015-07-15 08:23 UTC
Labels: Bug, Enhancement, Important

**Comment by GaelVaroquaux** [comment] 2015-07-15 09:18
> Closed #671.

We need this fixed, though. The whole doc building framework is broken
currently, and it's penalizing the sprint a lot.

**Comment by AlexandreAbraham** [comment] 2015-07-15 09:41
Can you clarify the problem? And why do people need to build the doc?

`make doc` should be working but yes, it requires heavy downloads.

**Comment by GaelVaroquaux** [comment] 2015-07-15 09:42
> Can you clarify the problem? And why do people need to build the doc?

> make doc should be working but yes, it requires heavy downloads.

Just 'make' should not require downloads

**Comment by AlexandreAbraham** [comment] 2015-07-15 10:14
> Just 'make' should not require downloads

`make` do not require downloads. It runs nosetests, which requires no data and doctest which are broken since last doc refactoring.

**Comment by GaelVaroquaux** [comment] 2015-07-15 10:15
> make do not require downloads. It runs nosetests, which requires no data and
> doctest which are broken since last doc refactoring.

That's issue #668

I am on it. Almost fixed

**Comment by AlexandreAbraham** [comment] 2015-07-15 10:19
Adding a few `# doctest: +SKIP` in `introduction.rst` worked for me!

**Comment by GaelVaroquaux** [comment] 2015-07-15 10:19
> Adding a few # doctest: +SKIP in introduction.rst worked for me!

Sent a PR

**Comment by GaelVaroquaux** [comment] 2015-07-15 10:26
> Just 'make' should not require downloads

We are not able to reproduce this problem. Probably a user error. This is
telling me that we need to work on developer documentation soon.

**Comment by AlexandreAbraham** [comment] 2015-07-15 10:27
I diagnosed it in #669. It's a sphinx problem.
