### ISSUE TITLE
Colorbar of plot_stat_map disappears when results are clipped

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#2579] opened 2020-10-11 20:51 UTC
I used `nilearn.plotting.plot_stat_map` to plot some results. However, when I clip the same results using a min value (concretely, I used numpy.clip with a_min=0) and plot them, the colorbar disappears.

**Comment by KamalakerDadi** [comment] 2020-10-12 05:19
I cannot reproduce with the script below.
```python
import nibabel
import numpy as np
from nilearn import datasets, plotting

img = datasets.fetch_localizer_button_task()
img = nibabel.load(img['cmaps'][0])
plotting.plot_stat_map(img)

data = img.get_fdata()
clipped_data = np.clip(data, a_min=0, a_max=data.max())
clipped_img = nibabel.Nifti1Image(clipped_data, affine=img.affine)
plotting.plot_stat_map(clipped_img)
plotting.show()
```

Do you have a script to reproduce?

**Comment by alpinho** [comment] 2020-10-12 11:47
I have created this small script that isolates my problem:

```python
import os

import numpy as np

from nilearn.input_data import NiftiMasker
from nilearn.plotting import plot_stat_map

import ibc_public.utils_data


def plotting(gmatter_mask, results, eval_metric, final_fig):
    masker = NiftiMasker(mask_img=gmatter_mask).fit()
    for name in ["FastSRM"]:
        plot_stat_map(masker.inverse_transform(results),
                      display_mode="z",
                      title='%s ' % name + eval_metric,
                      output_file=final_fig)


_package_directory = os.path.dirname(
    os.path.abspath(ibc_public.utils_data.__file__))
mask_gm = os.path.join(_package_directory,
                       '../ibc_data', 'gm_mask_1_5mm.nii.gz')


# Load results
r2_score = np.load('r2_scores.npy')
# Path of output file
r2_fig = os.path.join(os.path.dirname(__file__),
                      'r2_figure.png')
r2_fig_threshold0 = os.path.join(os.path.dirname(__file__),
                                 'r2_figure_threshold0.png')
# Clip r2-scores lower than 0 to 0
clipped_r2 = np.zeros_like(r2_score)
np.clip(r2_score, 0.0, None, out=clipped_r2)
# Plot the results
plotting(mask_gm, r2_score, 'R-squared', r2_fig)
plotting(mask_gm, clipped_r2, 'R-squared', r2_fig_threshold0)
```

You also need to download and unzip this file:
[r2_scores.zip](https://github.com/nilearn/nilearn/files/5364855/r2_scores.zip)

And install `ibc_public` from here: [https://github.com/hbp-brain-charting/public_analysis_code](url)

Nevertheless, I must say that I ran by chance this test function in a different environment and the problem disappeared. However, I still get it with this same test function in the original environment.

Original environment: python 3.6.9, nilearn 0.6.2, matplotlib 3.3.1
New environment: python 3.7.3, nilearn 0.5.2, matplotlib 3.0.3

**Comment by alpinho** [comment] 2020-10-12 16:50
Hello again,
I just reproduced the same problem in a different machine using the original environment. Yet, if I change environment by switching to the latest version of nilearn, i.e. '0.7.0a', and use matplotlib either 3.3.1 or 3.3.2 (the latest vs), the colobar appears again. So, perhaps, this is not a problem anymore.

**Comment by emdupre** [comment] 2020-10-14 17:59
Thanks for following up with this, @alpinho  ! 

At this point, if it's not reproducible with the newest version of Nilearn I'm not sure that we can address it. I'll let you close this if you can't trigger the error with 0.7.0a in either environment ?

**Comment by jeromedockes** [comment] 2020-10-14 18:15
Since the latest release there have been a couple of PRs to adapt to
breaking changes in matplotlib releases, eg #2431 dealing with a
colorbar issue. If the problem only appears with nilearn 0.6 maybe it
has been fixed already. However please let us know if you can reproduce
the problem with the nilearn master branch and any matplotlib version.

**Comment by alpinho** [comment] 2020-10-14 19:07
OK. I'll make a few more checks during the next days. If I don't find any problem I'll close the issue. Thanks!

**Closed** 2020-10-20 10:04 UTC
Labels: Bug
