### ISSUE TITLE
New dataset and example for decoding data

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1506] opened 2017-09-07 19:29 UTC
The images from the following paper:
http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002180
are available on
https://neurovault.org/collections/503/
and on
http://neurovault.org/collections/504/
and the emotion and pain ratings are available as meta data.

We could build an example that decodes emotion or pain using the neurovault dowloader. It would be super cool because it would add a decoding example with a different dataset (everybody is bored of Haxby, and the Jimura doesn't work well.

**Comment by ljchang** [comment] 2017-09-07 19:43
Great idea!  I'm happy to help contribute.  Here is a start using a different toolbox.  https://github.com/Summer-MIND/mind_2017/blob/master/Tutorials/Decoding/Chang_Decoding.ipynb

**Comment by nicofarr** [comment] 2017-11-16 15:48
I'm happy to try out this one. 
I'll try do some first tests on the smallest one (collection 504) although it's only 28 subjects with three pain ratings, and see whether it's worth doing a full nilearn example from there.

**Comment by nicofarr** [comment] 2017-11-18 04:57
First straightforward decoding example for 503 is [here](http://nbviewer.jupyter.org/gist/nicofarr/d73c8f611c0a77d4e989b11ae4a4033a) :  

And [here](http://nbviewer.jupyter.org/gist/nicofarr/1b0bccf636aa2a1c82ed7f07b528ea64) for 504. 

In both cases, a very straightforward decoding approach seems to yield acceptable results. 

I'll focus on collection 503 as it's the one that yields the largest number of images. 
A few things : 

- In the notebook above, I've randomly taken 700 images out of the 5000+ images availables, without controlling for anything. I didn't control for subjects. 

- It seems there are more examples for Rating 1 than the other ratings. 

- I also didn't take into account the train/test split that is present in the metadata, but rather I used 5-fold CV. 

- On 700 images, when training to classify Rating 1 vs Rating 5, we obtain a CV-accuracy of about 81% over folds. I've tried with 500 images and obtained a similar result. 



Suggestions regarding where to go from here : 
- Implement an example with the full regression over the rating values (using Lasso as in the paper ? ) 
- Implement an example with Searchlight 
- Implement an example with SpaceNetClassifier / SpaceNetRegressor 
- Generate a smaller list of images that correspond a subset of subjects and feed it to the Neurovault fetcher, so that the example doesn't download the 5000+ images

Any thoughts ?

**Comment by GaelVaroquaux** [comment] 2017-11-18 15:25
On Sat, Nov 18, 2017 at 04:57:03AM +0000, Nicolas Farrugia wrote:
> Suggestions regarding where to go from here :

>   • Implement an example with the full regression over the rating values (using
>     Lasso as in the paper ? )
>   • Implement an example with Searchlight
>   • Implement an example with SpaceNetClassifier / SpaceNetRegressor
>   • Generate a smaller list of images that correspond a subset of subjects and
>     feed it to the Neurovault fetcher, so that the example doesn't download the
>     5000+ images

> Any thoughts ?

In terms of examples, I'd like to consider replacing all the
mixed_gambles one: mixed_gambles doesn't work well.

And +1 for a smaller list of images in the download :)

**Comment by bthirion** [comment] 2017-11-20 22:36
Great proposition !

**Comment by kchawla-pi** [comment] 2018-10-08 07:28
@thomasbazeille THis one might be useful for you.

**Comment by nicofarr** [comment] 2020-05-21 15:21
Is this still relevant today ? @GaelVaroquaux examples have probably changed quite a bit since nov 2017. Do you think we should design an example using a neurovault collection, maybe using a small subset of one large collection, and use the resampling feature ?

**Comment by GaelVaroquaux** [comment] 2020-05-21 16:06
> Is this still relevant today ?

I think that what's most missing currently is an example where we run a
first-level and then do decoding on top of that.

The situation with regards to datasets and examples is however that we
are now very resource limited, as the CI takes forever to run and the
example downloads are brittle :(

**Comment by bthirion** [comment] 2020-05-21 16:17
> I think that what's most missing currently is an example where we run a first-level and then do decoding on top of that.

It exists already https://github.com/nilearn/nilearn/blob/master/examples/07_advanced/plot_haxby_block_classification.py

**Comment by GaelVaroquaux** [comment] 2020-05-21 16:23
> https://github.com/nilearn/nilearn/blob/master/examples/07_advanced/plot_haxby_block_classification.py

I wasn't happy with it, because it's a block design while I get a lot of
questions on event design. However, I agree that you are right, and that
it is good enough.

We should add more pointers to this example across the documentation
(including in the decoding tutorial).

**Comment by Remi-Gau** [comment] 2024-09-19 16:00
- given the last few messages, am gonna close this issue in favor of this one: https://github.com/nilearn/nilearn/issues/2425

**Closed by Remi-Gau** 2024-09-19 16:00 UTC
Labels: Enhancement, Good first issue, Datasets, Help wanted
