### ISSUE TITLE
Next steps for Mesh and Surface objects

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2681] opened 2021-02-03 09:24 UTC
Mesh and surface were introduced in #2474 and #2672.
The next steps are:

- [ ] Update related functions with backward compatibility
- [ ] Start deprecating previous usage
- [ ] Update documentation

**Comment by thomasbazeille** [comment] 2021-02-03 10:38
I think also this means #2424 is not blocked anymore. And in general Surface Maskers implementation can be done.

Once we have surface maskers, most of our object such as Decoder will be able to accept surface.

**Comment by NicolasGensollen** [comment] 2021-09-03 13:24
Linking [this discussion group](https://nipy.discourse.group/c/surface-api/10) about the surface API in Nibabel.

**Comment by NicolasGensollen** [comment] 2021-09-17 15:25
Linking this Nibabel PR : https://github.com/nipy/nibabel/pull/1056

**Comment by Remi-Gau** [comment] 2023-10-26 12:28
I feel that given the ongoing work on the Surface front, this issue is either a duplicate of a more recent one or would need to be made more specific to be useful.

Closing but feel free to reopen if you feel otherwise.

**Closed by Remi-Gau** 2023-10-26 12:28 UTC
Labels: Documentation, Enhancement, Surface
