### ISSUE TITLE
Improve docstrings: more technical details

### ISSUE THREAD

**Issue by albayenes** [nilearn/nilearn#1437] opened 2017-04-09 17:57 UTC
Hi,

I have been using nilearn for a few weeks already. Actually, I need more technical explanation many times because I cannot figure out what a function does from the name of the function. For example, To understand what fit_transform function does in NiftiLabelsMasker, I had to read code. But if there were a little explanation like "fit_transform calculates mean of the signal in the region", I would not have to read the code.

**Comment by GaelVaroquaux** [comment] 2017-11-06 21:22
Sorry, replying after a very long time.

I agree that quite often the docstrings could be improved. We're trying to work on it slowly. I think that you should feel free to send small PRs when you have a better version of a docstring.

I'll change the title of this issue to "Improve docsrings: more technical details", to make it easier to understand what it is about at a cursory look.

**Comment by bthirion** [comment] 2021-01-27 18:24
Still right, most likely, but the issue is not very useful as such. Closing.

**Closed by bthirion** 2021-01-27 18:24 UTC
